---
sidebar: sidebar 
permalink: concept-install-options-google.html 
keywords: install connector google cloud, google cloud install connector, connector google cloud, google cloud connector, install connector gcp, gcp install connector, connector gcp, gcp connector, installation options, manual install 
summary: 'Il existe plusieurs façons de créer un connecteur dans Google Cloud. La méthode la plus courante est d"accéder directement à BlueXP.' 
---
= Options d'installation de Connector dans Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il existe plusieurs façons de créer un connecteur dans Google Cloud. La méthode la plus courante est d'accéder directement à BlueXP.

Les options d'installation suivantes sont disponibles :

* link:task-install-connector-google-bluexp-gcloud.html["Créez le connecteur directement à partir de BlueXP"] (il s'agit de l'option standard)
+
Cette action lance une instance de serveur virtuel exécutant Linux et le logiciel Connector dans un VPC de votre choix.

* link:task-install-connector-google-bluexp-gcloud.html["Créer le connecteur à l'aide de gcloud"]
+
Cette action lance également une instance de VM exécutant Linux et le logiciel Connector, mais le déploiement est initié directement depuis Google Cloud plutôt que depuis BlueXP.

* link:task-install-connector-google-manual.html["Téléchargez et installez manuellement le logiciel sur votre propre hôte Linux"]


L'option d'installation que vous choisissez a une incidence sur la préparation de l'installation. Vous pouvez notamment fournir à BlueXP les autorisations requises pour authentifier et gérer les ressources dans Google Cloud.
