---
sidebar: sidebar 
permalink: concept-connectors.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery, agent' 
summary: 'Un connecteur est un logiciel NetApp exécuté sur votre réseau cloud ou sur site. Il exécute les actions que BlueXP doit exécuter pour gérer votre infrastructure de données. Le connecteur interroge constamment la couche SaaS BlueXP afin de détecter les actions à entreprendre. Vous n"avez pas besoin d"un connecteur pour démarrer avec BlueXP, mais vous devez créer un connecteur pour déverrouiller toutes les fonctionnalités et tous les services BlueXP.' 
---
= En savoir plus sur les connecteurs
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Un _connecteur_ est un logiciel NetApp s'exécutant dans votre réseau cloud ou sur site. Il exécute les actions que BlueXP doit exécuter pour gérer votre infrastructure de données. Le connecteur interroge en permanence la couche BlueXP  en tant que service (SaaS) afin de détecter les actions à entreprendre. Vous n'avez pas besoin d'un connecteur pour démarrer avec BlueXP, mais vous devez créer un connecteur pour déverrouiller toutes les fonctionnalités et tous les services BlueXP.



== Ce que vous pouvez faire sans connecteur

Il n'est pas nécessaire de disposer d'un connecteur pour démarrer avec BlueXP. Vous pouvez utiliser plusieurs fonctionnalités et services au sein de BlueXP sans créer de connecteur.

Vous pouvez utiliser les fonctionnalités et services BlueXP suivants sans connecteur :

* Amazon FSX pour NetApp ONTAP
+
Certaines actions nécessitent un connecteur ou une liaison d'usine de la charge de travail BlueXP . https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/concept-fsx-aws.html["Apprenez quelles actions nécessitent un connecteur ou un lien"^]

* Catalogue d'automatisation
* Azure NetApp Files
+
Aucun connecteur n'est nécessaire pour configurer et gérer Azure NetApp Files, mais vous devez utiliser un connecteur pour analyser les données Azure NetApp Files à l'aide de la classification BlueXP.

* Cloud Volumes Service pour Google Cloud
* Copie et synchronisation
* Conseiller digital
* Portefeuille numérique (licences uniquement, la surveillance des abonnements nécessite un connecteur)
+
Dans presque tous les cas, vous pouvez ajouter une licence au portefeuille numérique sans connecteur.

+
La seule fois qu'un connecteur est nécessaire pour ajouter une licence au portefeuille numérique est pour les licences Cloud Volumes ONTAP _basées sur le nœud_. Dans ce cas, un connecteur est requis car les données sont extraites des licences installées sur les systèmes Cloud Volumes ONTAP.

* Découverte directe des clusters ONTAP sur site
+
Même si aucun connecteur n'est nécessaire pour la découverte directe d'un cluster ONTAP sur site, un connecteur est nécessaire pour tirer parti des fonctionnalités BlueXP supplémentaires.

+
https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["En savoir plus sur les options de découverte et de gestion des clusters ONTAP sur site"^]

* Mises à jour de logiciels
* Durabilité
* Usine de charge de travail




== Lorsqu'un connecteur est nécessaire

Lorsque vous utilisez BlueXP en mode standard, un connecteur est requis pour les fonctionnalités et les services suivants dans BlueXP :

* Alertes
* Fonctions de gestion d'Amazon FSX pour ONTAP
* Le stockage Amazon S3
* Stockage Azure Blob
* Sauvegarde et restauration
* Classement
* Cloud Volumes ONTAP
* Reprise après incident
* Systèmes E-Series
* Efficacité économique ^1^
* Compartiments de stockage Google Cloud
* Intégration de clusters ONTAP sur site avec les services de données BlueXP
* Résilience opérationnelle ^1^
* Protection par ransomware
* Systèmes StorageGRID
* Tiering
* Mise en cache du volume


^1^ bien que vous puissiez accéder à ces services sans connecteur, un connecteur est nécessaire pour lancer des actions à partir des services.

Un connecteur est nécessaire pour utiliser BlueXP en mode restreint ou privé.



== Les connecteurs doivent toujours être opérationnels

Les connecteurs sont un élément fondamental de l'architecture de service BlueXP. Il est de votre responsabilité de vous assurer que les connecteurs appropriés sont en place, opérationnels et accessibles à tout moment. Bien que le service soit conçu pour surmonter les courtes pannes de la disponibilité des connecteurs, vous devez prendre des mesures immédiates pour remédier aux défaillances de l'infrastructure.

Cette documentation est régie par le CLUF. Si le produit n'est pas utilisé conformément à la documentation, la fonctionnalité et le fonctionnement du produit, ainsi que vos droits en vertu du CLUF, peuvent être affectés.



=== Impact sur Cloud Volumes ONTAP

Un connecteur est un composant clé de l'intégrité et du fonctionnement de Cloud Volumes ONTAP. Si un connecteur est hors tension, les systèmes Cloud Volumes ONTAP PAYGO et les systèmes BYOL basés sur la capacité sont arrêtés après avoir perdu la communication avec un connecteur pendant plus de 14 jours. Cela se produit car le connecteur actualise les licences du système chaque jour.

Si votre système Cloud Volumes ONTAP dispose d'une licence BYOL basée sur des nœuds, le système reste opérationnel au bout de 14 jours, car la licence est installée sur le système Cloud Volumes ONTAP.



== Emplacements pris en charge

Un connecteur est pris en charge aux emplacements suivants :

* Amazon Web Services
* Microsoft Azure
+
Un connecteur dans Azure doit être déployé dans la même région Azure que les systèmes Cloud Volumes ONTAP qu'il gère, ou dans le https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Paire de régions Azure"^] Pour les systèmes Cloud Volumes ONTAP. Cette exigence garantit qu'une connexion Azure Private Link est utilisée entre Cloud Volumes ONTAP et les comptes de stockage associés. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-enabling-private-link.html["Découvrez comment Cloud Volumes ONTAP utilise une liaison privée Azure"^]

* Google Cloud
+
Si vous souhaitez utiliser les services BlueXP avec Google Cloud, vous devez utiliser un connecteur exécuté dans Google Cloud.

* Sur site




== Communication avec les fournisseurs cloud

Le connecteur utilise TLS 1.2 pour toutes les communications vers AWS, Azure et Google Cloud.



== Mode restreint et mode privé

Pour utiliser BlueXP en mode restreint ou privé, vous commencez à utiliser BlueXP en installant le connecteur, puis en accédant à l'interface utilisateur qui s'exécute localement sur le connecteur.

link:concept-modes.html["Découvrez les modes de déploiement BlueXP"].



== Comment créer un connecteur

Vous pouvez créer un connecteur directement à partir de BlueXP , du Marketplace de votre fournisseur de cloud ou en installant manuellement le logiciel sur votre propre hôte Linux. La manière de commencer dépend si vous utilisez BlueXP en mode standard, en mode restreint ou en mode privé.

* link:concept-modes.html["Découvrez les modes de déploiement BlueXP"]
* link:task-quick-start-standard-mode.html["Commencez à utiliser BlueXP en mode standard"]
* link:task-quick-start-restricted-mode.html["Démarrez avec BlueXP en mode restreint"]
* link:task-quick-start-private-mode.html["Commencez à utiliser BlueXP en mode privé"]




== Autorisations

Des autorisations spécifiques sont nécessaires pour créer le connecteur directement à partir de BlueXP et un autre ensemble d'autorisations est nécessaire pour l'instance de connecteur elle-même. Si vous créez le connecteur dans AWS ou Azure directement à partir de BlueXP, BlueXP crée le connecteur avec les autorisations dont il a besoin.

Lorsque vous utilisez BlueXP en mode standard, la façon dont vous fournissez les autorisations dépend de la façon dont vous prévoyez de créer le connecteur.

Pour savoir comment configurer des autorisations, consultez les sections suivantes :

* Mode standard
+
** link:concept-install-options-aws.html["Options d'installation des connecteurs dans AWS"]
** link:concept-install-options-azure.html["Options d'installation des connecteurs dans Azure"]
** link:concept-install-options-google.html["Options d'installation de Connector dans Google Cloud"]
** link:task-install-connector-on-prem.html#step-4-set-up-cloud-permissions["Configurez les autorisations cloud pour les déploiements sur site"]


* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["Définissez les autorisations pour le mode restreint"]
* link:task-prepare-private-mode.html#step-6-prepare-cloud-permissions["Configurez les autorisations pour le mode privé"]


Pour afficher les autorisations exactes dont le connecteur a besoin pour les opérations quotidiennes, reportez-vous aux pages suivantes :

* link:reference-permissions-aws.html["Découvrez comment Connector utilise les autorisations AWS"]
* link:reference-permissions-azure.html["Découvrez comment le connecteur utilise les autorisations Azure"]
* link:reference-permissions-gcp.html["Découvrez comment Connector utilise les autorisations Google Cloud"]


Il est de votre responsabilité de mettre à jour les stratégies de connecteur lorsque de nouvelles autorisations sont ajoutées dans les versions ultérieures. Si de nouvelles autorisations sont requises, elles seront répertoriées dans les notes de version.



== Mises à niveau des connecteurs

Nous mettons généralement à jour le logiciel de connecteur chaque mois pour introduire de nouvelles fonctions et améliorer la stabilité. Bien que la plupart des services et fonctionnalités de la plateforme BlueXP  soient proposés via un logiciel SaaS, quelques fonctionnalités dépendent de la version du connecteur. Qui inclut la gestion Cloud Volumes ONTAP, la gestion de clusters ONTAP sur site, la configuration et l'aide.

Lorsque vous utilisez BlueXP en mode standard ou restreint, le connecteur met automatiquement à jour ses logiciels vers la dernière version, tant qu'il dispose d'un accès Internet sortant pour obtenir la mise à jour logicielle. Si vous utilisez BlueXP en mode privé, vous devez mettre à niveau manuellement le connecteur.

link:task-upgrade-connector.html["Apprenez à mettre à niveau manuellement le logiciel Connector lorsque vous utilisez le mode privé"].



== Maintenance du système d'exploitation et des machines virtuelles

La maintenance du système d'exploitation sur l'hôte du connecteur relève de votre responsabilité. Par exemple, vous devez appliquer des mises à jour de sécurité au système d'exploitation sur l'hôte du connecteur en suivant les procédures standard de votre entreprise pour la distribution du système d'exploitation.

Notez que vous n'avez pas besoin d'arrêter les services sur l'hôte du connecteur lors de l'application de mises à jour de sécurité mineures.

Si vous devez arrêter puis démarrer le connecteur VM, vous devez le faire depuis la console de votre fournisseur cloud ou en utilisant les procédures standard de gestion sur site.

<<Les connecteurs doivent toujours être opérationnels,Notez que le connecteur doit être opérationnel en permanence>>.



== Plusieurs environnements de travail et connecteurs

Un connecteur peut gérer plusieurs environnements de travail dans BlueXP. Le nombre maximum d'environnements de travail qu'un seul connecteur doit gérer varie. Cela dépend du type d'environnements de travail, du nombre de volumes, de la capacité gérée et du nombre d'utilisateurs.

Si vous disposez d'un déploiement à grande échelle, contactez votre représentant NetApp pour dimensionner votre environnement. Si vous rencontrez des problèmes pendant le trajet, contactez-nous en utilisant le chat produit.

Dans certains cas, vous n'avez peut-être besoin que d'un seul connecteur, mais vous pourriez avoir besoin de deux connecteurs ou plus.

Voici quelques exemples :

* Vous avez un environnement multicloud (AWS et Azure, par exemple) et vous préférez avoir un connecteur dans AWS et un autre dans Azure. Chacun gère les systèmes Cloud Volumes ONTAP exécutés dans ces environnements.
* Un fournisseur de services peut faire appel à une organisation BlueXP  pour fournir des services à ses clients, tandis qu'une autre entreprise fournit une reprise sur incident à l'une de ses unités commerciales. Chaque organisation aurait des connecteurs distincts.

