---
sidebar: sidebar 
permalink: concept-overview.html 
keywords: overview, concepts, features, use case, cloud manager, bluexp, how bluexp works, supported cloud providers, cloud providers, hyperscalers 
summary: 'NetApp BlueXP fournit à votre entreprise un plan de contrôle unique qui vous permet de créer, de protéger et de régir les données dans vos environnements sur site et cloud. La plateforme SaaS BlueXP inclut des services de gestion du stockage, de mobilité des données, de protection, d"analyse et de contrôle des données. Les fonctionnalités de gestion sont fournies via une console Web et des API.' 
---
= En savoir plus sur BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp BlueXP fournit à votre entreprise un plan de contrôle unique qui vous permet de créer, de protéger et de régir les données dans vos environnements sur site et cloud. La plateforme SaaS BlueXP inclut des services de gestion du stockage, de mobilité des données, de protection, d'analyse et de contrôle des données. Les fonctionnalités de gestion sont fournies via une console Web et des API.



== Caractéristiques

La plateforme BlueXP offre quatre piliers fondamentaux pour la gestion des données : stockage, mobilité, protection, analyse et contrôle.

Stockage:: Découvrez, déployez et gérez le stockage, que ce soit dans AWS, Azure, Google Cloud ou sur site.
+
--
* Configurez et utilisez les services cloud de stockage de fichiers :
+
** https://bluexp.netapp.com/azure-netapp-files["Azure NetApp Files"^]
** https://bluexp.netapp.com/fsx-for-ontap["Amazon FSX pour NetApp ONTAP"^]
** https://bluexp.netapp.com/cloud-volumes-service-for-gcp["Cloud Volumes Service pour Google Cloud"^]


* Configuration et utilisation https://bluexp.netapp.com/ontap-cloud["Cloud Volumes ONTAP"^] pour une gestion efficace des données multiprotocole sur l'ensemble des clouds.
* Détection et gestion https://bluexp.netapp.com/netapp-on-premises["le stockage sur site"^]:
+
** Systèmes E-Series
** Clusters ONTAP
** Systèmes StorageGRID




--
Mobilité:: Déplacez vos données là où vous en avez besoin grâce à la synchronisation, la copie et le Tiering.
+
--
* https://bluexp.netapp.com/cloud-sync-service["Copie et synchronisation"^]
* https://bluexp.netapp.com/cloud-tiering["Tiering"^]


--
La protection:: Utilisez des mécanismes de protection automatisés pour protéger vos données contre les pertes de données, les pannes imprévues, les ransomware et autres cybermenaces.
+
--
* https://bluexp.netapp.com/cloud-backup["Sauvegarde et restauration"^]
* https://bluexp.netapp.com/disaster-recovery["Reprise après incident"^]
* https://bluexp.netapp.com/replication["La réplication"^]
* https://bluexp.netapp.com/ransomware-protection["Protection par ransomware"^]


--
Analyse et contrôle:: Utilisez des outils pour surveiller, cartographier et optimiser votre infrastructure et votre stockage de données. Bénéficiez d'informations exploitables pour optimiser l'état, la résilience et les coûts du stockage.
+
--
* https://bluexp.netapp.com/netapp-cloud-data-sense["Classement"^]
* https://bluexp.netapp.com/digital-advisor["Conseiller digital"^]
* https://bluexp.netapp.com/digital-advisor["Efficacité économique"^]
* https://bluexp.netapp.com/digital-advisor["Résilience opérationnelle"^]


--


https://bluexp.netapp.com/["Découvrez comment utiliser BlueXP  pour gérer les données dans l'ensemble de votre environnement multicloud hybride"^]



== Fournisseurs cloud pris en charge

BlueXP vous permet de gérer le stockage cloud et d'utiliser les services cloud dans Amazon Web Services, Microsoft Azure et Google Cloud.



== Le coût

Le prix de BlueXP dépend des services que vous prévoyez d'utiliser. https://bluexp.netapp.com/pricing["En savoir plus sur les tarifs BlueXP"^]



== Fonctionnement de BlueXP

BlueXP  comprend une console Web fournie via la couche SaaS, un système de gestion des ressources et des accès, ainsi que des connecteurs qui gèrent les environnements de travail et activent les services clouds BlueXP .



=== Services à la demande

BlueXP  est accessible via https://console.bluexp.netapp.com["console web"^] les API et. Cette expérience SaaS vous permet d'accéder automatiquement aux dernières fonctionnalités dès leur sortie et de basculer facilement entre vos organisations, projets et connecteurs BlueXP .



=== Gestion des identités et des accès BlueXP 

Le modèle de gestion des accès et des identités BlueXP  offre une gestion granulaire des ressources et des autorisations :

* Une _organisation_ de haut niveau vous permet de gérer l'accès à vos différents _projets_
* _Dossiers_ vous permet de regrouper des projets associés
* La gestion des ressources vous permet d'associer une ressource à un ou plusieurs dossiers ou projets
* La gestion des accès vous permet d'attribuer un rôle aux membres à différents niveaux de la hiérarchie de l'organisation


BlueXP  IAM est pris en charge lorsque BlueXP  est utilisé en mode standard. Si vous utilisez BlueXP  en mode restreint ou privé, vous utiliserez un _compte_ BlueXP  pour gérer les espaces de travail, les utilisateurs et les ressources.

* link:concept-identity-and-access-management.html["En savoir plus sur BlueXP  IAM"]
* link:concept-netapp-accounts.html["Découvrez les comptes BlueXP"]




=== Connecteurs

Vous n'avez pas besoin d'un connecteur pour démarrer avec BlueXP, mais vous devez créer un connecteur pour déverrouiller toutes les fonctionnalités et tous les services BlueXP. Un connecteur vous permet de gérer les ressources et les processus dans vos environnements sur site et cloud. Il est nécessaire de gérer les environnements de travail (par exemple, Cloud Volumes ONTAP) et d'utiliser de nombreux services BlueXP .

link:concept-connectors.html["En savoir plus sur les connecteurs"].



=== Modes de déploiement

BlueXP  est pris en charge dans les environnements soumis à des restrictions de sécurité et de connectivité. Vous pouvez utiliser _restricted mode_ ou _private mode_ pour limiter la connectivité sortante à la couche SaaS de BlueXP.

link:concept-modes.html["En savoir plus sur les modes de déploiement BlueXP"].



== Certification SOC 2 Type 2

Un comptable public indépendant et un vérificateur des services ont examiné BlueXP et confirmé qu'il a obtenu des rapports SOC 2 de type 2 en fonction des critères des services de fiducie applicables.

https://www.netapp.com/company/trust-center/compliance/soc-2/["Consultez les rapports SOC 2 de NetApp"^]
