---
sidebar: sidebar 
permalink: concept-connectors.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery' 
summary: 'Un connecteur est un logiciel NetApp exécuté sur votre réseau cloud ou sur site. Il exécute les actions que BlueXP doit exécuter pour gérer votre infrastructure de données. Le connecteur interroge constamment la couche SaaS BlueXP afin de détecter les actions à entreprendre. Vous n"avez pas besoin d"un connecteur pour démarrer avec BlueXP, mais vous devez créer un connecteur pour déverrouiller toutes les fonctionnalités et tous les services BlueXP.' 
---
= En savoir plus sur les connecteurs
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Un _connecteur_ est un logiciel NetApp s'exécutant dans votre réseau cloud ou sur site. Il exécute les actions que BlueXP doit exécuter pour gérer votre infrastructure de données. Le connecteur interroge constamment la couche SaaS BlueXP afin de détecter les actions à entreprendre. Vous n'avez pas besoin d'un connecteur pour démarrer avec BlueXP, mais vous devez créer un connecteur pour déverrouiller toutes les fonctionnalités et tous les services BlueXP.



== Ce que vous pouvez faire sans connecteur

Il n'est pas nécessaire de disposer d'un connecteur pour démarrer avec BlueXP. Vous pouvez utiliser plusieurs fonctionnalités et services au sein de BlueXP sans créer de connecteur.

Vous pouvez utiliser les fonctionnalités et services BlueXP suivants sans connecteur :

* Création d'un environnement de travail Amazon FSX pour NetApp ONTAP
+
Aucun connecteur n'est nécessaire pour créer un environnement de travail, mais il est nécessaire de créer et de gérer des volumes, de répliquer des données et d'intégrer FSX pour ONTAP avec des services tels que la classification BlueXP et la copie et la synchronisation BlueXP.

* Catalogue d'automatisation
* Azure NetApp Files
+
Aucun connecteur n'est nécessaire pour configurer et gérer Azure NetApp Files, mais vous devez utiliser un connecteur pour analyser les données Azure NetApp Files à l'aide de la classification BlueXP.

* Cloud Volumes Service pour Google Cloud
* Copie et synchronisation
* Conseiller digital
* Portefeuille digital
+
Dans presque tous les cas, vous pouvez ajouter une licence au portefeuille numérique sans connecteur.

+
La seule fois qu'un connecteur est nécessaire pour ajouter une licence au portefeuille numérique est pour les licences Cloud Volumes ONTAP _basées sur le nœud_. Dans ce cas, un connecteur est requis car les données sont extraites des licences installées sur les systèmes Cloud Volumes ONTAP.

* Découverte directe des clusters ONTAP sur site
+
Même si aucun connecteur n'est nécessaire pour la découverte directe d'un cluster ONTAP sur site, un connecteur est nécessaire pour tirer parti des fonctionnalités BlueXP supplémentaires.

+
https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["En savoir plus sur les options de découverte et de gestion des clusters ONTAP sur site"^]

* Durabilité




== Lorsqu'un connecteur est nécessaire

Lorsque vous utilisez BlueXP en mode standard, un connecteur est requis pour les fonctionnalités et les services suivants dans BlueXP :

* Fonctions de gestion d'Amazon FSX pour ONTAP
* Le stockage Amazon S3
* Stockage Azure Blob
* Sauvegarde et restauration
* Classement
* Cloud Volumes ONTAP
* Reprise après incident
* Systèmes E-Series
* Efficacité économique ^1^
* La mise en cache en périphérie
* Compartiments de stockage Google Cloud
* Clusters Kubernetes
* Rapports de migration
* Intégration de clusters ONTAP sur site avec les services de données BlueXP
* Résilience opérationnelle ^1^
* Protection par ransomware
* Systèmes StorageGRID
* Tiering
* Mise en cache du volume


^1^ bien que vous puissiez accéder à ces services sans connecteur, un connecteur est nécessaire pour lancer des actions à partir des services.

Un connecteur est nécessaire pour utiliser BlueXP en mode restreint ou privé.



== Les connecteurs doivent toujours être opérationnels

Les connecteurs sont un élément fondamental de l'architecture de service BlueXP. Il est de votre responsabilité de vous assurer que les connecteurs appropriés sont en place, opérationnels et accessibles à tout moment. Bien que le service soit conçu pour surmonter les courtes pannes de la disponibilité des connecteurs, vous devez prendre des mesures immédiates pour remédier aux défaillances de l'infrastructure.

Cette documentation est régie par le CLUF. Si le produit n'est pas utilisé conformément à la documentation, la fonctionnalité et le fonctionnement du produit, ainsi que vos droits en vertu du CLUF, peuvent être affectés.



=== Impact sur Cloud Volumes ONTAP

Un connecteur est un composant clé de l'intégrité et du fonctionnement de Cloud Volumes ONTAP. Si un connecteur est hors tension, les systèmes Cloud Volumes ONTAP PAYGO et les systèmes BYOL basés sur la capacité sont arrêtés après avoir perdu la communication avec un connecteur pendant plus de 14 jours. Cela se produit car le connecteur actualise les licences du système chaque jour.

Si votre système Cloud Volumes ONTAP dispose d'une licence BYOL basée sur des nœuds, le système reste opérationnel au bout de 14 jours, car la licence est installée sur le système Cloud Volumes ONTAP.



== Emplacements pris en charge

Un connecteur est pris en charge aux emplacements suivants :

* Amazon Web Services
* Microsoft Azure
+
Un connecteur dans Azure doit être déployé dans la même région Azure que les systèmes Cloud Volumes ONTAP qu'il gère, ou dans le https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Paire de régions Azure"^] Pour les systèmes Cloud Volumes ONTAP. Cette exigence garantit qu'une connexion Azure Private Link est utilisée entre Cloud Volumes ONTAP et les comptes de stockage associés. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-enabling-private-link.html["Découvrez comment Cloud Volumes ONTAP utilise une liaison privée Azure"^]

* Google Cloud
+
Si vous souhaitez utiliser les services BlueXP avec Google Cloud, vous devez utiliser un connecteur exécuté dans Google Cloud.

* Sur site




== Mode restreint et mode privé

Pour utiliser BlueXP en mode restreint ou privé, vous commencez à utiliser BlueXP en installant le connecteur, puis en accédant à l'interface utilisateur qui s'exécute localement sur le connecteur.

link:concept-modes.html["Découvrez les modes de déploiement BlueXP"].



== Comment créer un connecteur

Un administrateur de compte BlueXP peut créer un connecteur directement à partir de BlueXP, du marché de votre fournisseur cloud ou en installant manuellement le logiciel sur votre propre hôte Linux. La manière de commencer dépend si vous utilisez BlueXP en mode standard, en mode restreint ou en mode privé.

* link:concept-modes.html["Découvrez les modes de déploiement BlueXP"]
* link:task-quick-start-standard-mode.html["Commencez à utiliser BlueXP en mode standard"]
* link:task-quick-start-restricted-mode.html["Démarrez avec BlueXP en mode restreint"]
* link:task-quick-start-private-mode.html["Commencez à utiliser BlueXP en mode privé"]




== Autorisations

Des autorisations spécifiques sont nécessaires pour créer le connecteur directement à partir de BlueXP et un autre ensemble d'autorisations est nécessaire pour l'instance de connecteur elle-même. Si vous créez le connecteur dans AWS ou Azure directement à partir de BlueXP, BlueXP crée le connecteur avec les autorisations dont il a besoin.

Lorsque vous utilisez BlueXP en mode standard, la façon dont vous fournissez les autorisations dépend de la façon dont vous prévoyez de créer le connecteur.

Pour savoir comment configurer des autorisations, consultez les sections suivantes :

* Mode standard
+
** link:concept-install-options-aws.html["Options d'installation des connecteurs dans AWS"]
** link:concept-install-options-azure.html["Options d'installation des connecteurs dans Azure"]
** link:concept-install-options-google.html["Options d'installation de Connector dans Google Cloud"]
** link:task-install-connector-on-prem.html#step-3-set-up-cloud-permissions["Configurez les autorisations cloud pour les déploiements sur site"]


* link:task-prepare-restricted-mode.html#step-5-prepare-cloud-permissions["Définissez les autorisations pour le mode restreint"]
* link:task-prepare-private-mode.html#step-5-prepare-cloud-permissions["Configurez les autorisations pour le mode privé"]


Pour afficher les autorisations exactes dont le connecteur a besoin pour les opérations quotidiennes, reportez-vous aux pages suivantes :

* link:reference-permissions-aws.html["Découvrez comment Connector utilise les autorisations AWS"]
* link:reference-permissions-azure.html["Découvrez comment le connecteur utilise les autorisations Azure"]
* link:reference-permissions-gcp.html["Découvrez comment Connector utilise les autorisations Google Cloud"]




== Mises à niveau des connecteurs

Nous mettons généralement à jour le logiciel de connecteur chaque mois pour introduire de nouvelles fonctions et améliorer la stabilité. Bien que la plupart des services et fonctionnalités de la plate-forme BlueXP soient proposés par le logiciel SaaS, quelques fonctionnalités dépendent de la version du connecteur. Qui inclut la gestion Cloud Volumes ONTAP, la gestion de clusters ONTAP sur site, la configuration et l'aide.

Lorsque vous utilisez BlueXP en mode standard ou restreint, le connecteur met automatiquement à jour ses logiciels vers la dernière version, tant qu'il dispose d'un accès Internet sortant pour obtenir la mise à jour logicielle. Si vous utilisez BlueXP en mode privé, vous devez mettre à niveau manuellement le connecteur.

link:task-managing-connectors.html["Apprenez à mettre à niveau manuellement le logiciel du connecteur"].



== Maintenance du système d'exploitation et des machines virtuelles

La maintenance du système d'exploitation sur l'hôte du connecteur relève de votre responsabilité. Par exemple, vous devez appliquer des mises à jour de sécurité au système d'exploitation sur l'hôte du connecteur en suivant les procédures standard de votre entreprise pour la distribution du système d'exploitation.

Notez que vous n'avez pas besoin d'arrêter les services sur l'hôte du connecteur lors de l'exécution d'une mise à jour du système d'exploitation.

Si vous devez arrêter puis démarrer le connecteur VM, vous devez le faire depuis la console de votre fournisseur cloud ou en utilisant les procédures standard de gestion sur site.

<<Les connecteurs doivent toujours être opérationnels,Notez que le connecteur doit être opérationnel en permanence>>.



== Plusieurs environnements de travail

Un connecteur peut gérer plusieurs environnements de travail dans BlueXP. Le nombre maximum d'environnements de travail qu'un seul connecteur doit gérer varie. Cela dépend du type d'environnements de travail, du nombre de volumes, de la capacité gérée et du nombre d'utilisateurs.

Si vous disposez d'un déploiement à grande échelle, contactez votre représentant NetApp pour dimensionner votre environnement. Si vous rencontrez des problèmes pendant le trajet, contactez-nous en utilisant le chat produit.



== Connecteurs multiples

Dans certains cas, vous n'avez peut-être besoin que d'un seul connecteur, mais vous pourriez avoir besoin de deux connecteurs ou plus.

Voici quelques exemples :

* Vous avez un environnement multicloud (AWS et Azure, par exemple) et vous préférez avoir un connecteur dans AWS et un autre dans Azure. Chacun gère les systèmes Cloud Volumes ONTAP exécutés dans ces environnements.
* Un fournisseur de services peut utiliser un compte BlueXP pour fournir des services à ses clients, tout en utilisant un autre compte pour assurer la reprise après incident pour l'une de ses unités commerciales. Chaque compte aurait des connecteurs distincts.




=== Quand changer

Lorsque vous créez votre premier connecteur, BlueXP utilise automatiquement ce connecteur pour chaque environnement de travail supplémentaire créé. Une fois que vous avez créé un connecteur supplémentaire, vous devrez passer de l'un à l'autre pour voir les environnements de travail spécifiques à chaque connecteur.

link:task-managing-connectors.html["Apprenez à passer d'un connecteur à un autre"].



=== Reprise après incident

Vous pouvez gérer un environnement de travail à l'aide de plusieurs connecteurs en même temps pour la reprise après sinistre. Si un connecteur tombe en panne, vous pouvez passer à l'autre connecteur pour gérer immédiatement l'environnement de travail.

Pour configurer cette configuration :

. link:task-managing-connectors.html["Basculer vers un autre connecteur"].
. Découvrir l'environnement de travail existant
+
** https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-adding-systems.html["Ajout de systèmes Cloud Volumes ONTAP existants à BlueXP"^]
** https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["Découvrir les clusters ONTAP"^]


. Réglez le https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-storage-management.html["Mode de gestion de la capacité"^]
+
Seul le connecteur principal doit être réglé sur *mode automatique*. Si vous basculez vers un autre connecteur pour la reprise après incident, vous pouvez modifier le mode de gestion de la capacité selon vos besoins.


