---
sidebar: sidebar 
permalink: concept-install-options-aws.html 
keywords: install connector aws, aws install connector, connector aws, aws connector, installation options, aws marketplace, manual install, deploy 
summary: 'Il existe plusieurs façons de créer un connecteur dans AWS. La méthode la plus courante est d"accéder directement à BlueXP.' 
---
= Options d'installation des connecteurs dans AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il existe plusieurs façons de créer un connecteur dans AWS. La méthode la plus courante est d'accéder directement à BlueXP.

Les options d'installation suivantes sont disponibles :

* link:task-install-connector-aws-bluexp.html["Créez le connecteur directement à partir de BlueXP"] (il s'agit de l'option standard)
+
Cette action lance une instance EC2 exécutant Linux et le logiciel Connector dans un VPC de votre choix.

* link:task-install-connector-aws-marketplace.html["Créez un connecteur à partir d'AWS Marketplace"]
+
Cette action lance également une instance EC2 exécutant Linux et le logiciel Connector, mais le déploiement est initié directement à partir d'AWS Marketplace plutôt que de BlueXP.

* link:task-install-connector-aws-manual.html["Téléchargez et installez manuellement le logiciel sur votre propre hôte Linux"]


L'option d'installation que vous choisissez a une incidence sur la préparation de l'installation. Vous pouvez notamment fournir à BlueXP les autorisations requises pour authentifier et gérer les ressources dans AWS.
