---
sidebar: sidebar 
permalink: concept-install-options-azure.html 
keywords: install connector azure, azure install connector, connector azure, azure connector, installation options, azure marketplace, manual install 
summary: 'Il existe plusieurs façons de créer un connecteur dans Azure. La méthode la plus courante est d"accéder directement à BlueXP.' 
---
= Options d'installation des connecteurs dans Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il existe plusieurs façons de créer un connecteur dans Azure. La méthode la plus courante est d'accéder directement à BlueXP. L'option d'installation que vous choisissez détermine la manière dont vous préparez le déploiement.

Les options d'installation suivantes sont disponibles :

* Créez le connecteur directement à partir de BlueXP (il s'agit de l'option standard).
+
Cette action lance une machine virtuelle exécutant Linux et le logiciel Connector dans un réseau virtuel de votre choix.

* Créez un connecteur à partir d'Azure Marketplace
+
Cette action lance également une machine virtuelle exécutant Linux et le logiciel Connector.

* Téléchargez et installez manuellement le logiciel sur votre propre hôte Linux


L'option d'installation que vous choisissez a une incidence sur la préparation de l'installation. Vous pouvez notamment fournir à BlueXP les autorisations requises pour authentifier et gérer les ressources dans Azure.

link:task-install-connector-azure.html["Découvrez comment installer le connecteur dans Azure"].
