---
settings:
  name: Setup and administration
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documents de configuration et d'administration
    url: "/index.html"
  - title: Notes de mise à jour
    entries:
    - title: Quoi de neuf
      url: "/whats-new.html"
    - title: Limites connues
      url: "/reference-limitations.html"
  - title: Commencez
    entries:
    - title: Découvrez les bases
      entries:
      - title: BlueXP
        url: "/concept-overview.html"
      - title: Comptes
        url: "/concept-netapp-accounts.html"
      - title: Connecteurs
        url: "/concept-connectors.html"
      - title: Modes de déploiement
        url: "/concept-modes.html"
    - title: Commencez avec le mode standard
      entries:
      - title: Mise en route du flux de travail
        url: "/task-quick-start-standard-mode.html"
      - title: Préparez la mise en réseau à l'aide de la console BlueXP
        url: "/reference-networking-saas-console.html"
      - title: Inscrivez-vous à BlueXP
        url: "/task-sign-up-saas.html"
      - title: Créer un connecteur
        entries:
        - title: AWS
          entries:
          - title: Options d'installation du connecteur
            url: "/concept-install-options-aws.html"
          - title: Créez un connecteur depuis BlueXP
            url: "/task-install-connector-aws-bluexp.html"
          - title: Créez un connecteur à partir du Marketplace
            url: "/task-install-connector-aws-marketplace.html"
          - title: Installer manuellement le connecteur
            url: "/task-install-connector-aws-manual.html"
        - title: Azure
          entries:
          - title: Options d'installation du connecteur
            url: "/concept-install-options-azure.html"
          - title: Créez un connecteur depuis BlueXP
            url: "/task-install-connector-azure-bluexp.html"
          - title: Créez un connecteur à partir du Marketplace
            url: "/task-install-connector-azure-marketplace.html"
          - title: Installer manuellement le connecteur
            url: "/task-install-connector-azure-manual.html"
        - title: Google Cloud
          entries:
          - title: Options d'installation du connecteur
            url: "/concept-install-options-google.html"
          - title: Créez un connecteur à partir de BlueXP ou de gcloud
            url: "/task-install-connector-google-bluexp-gcloud.html"
          - title: Installer manuellement le connecteur
            url: "/task-install-connector-google-manual.html"
        - title: Sur site
          url: "/task-install-connector-on-prem.html"
      - title: Abonnez-vous à BlueXP
        url: "/task-subscribe-standard-mode.html"
      - title: Que pouvez-vous faire ensuite
        url: "/reference-whats-next.html"
    - title: Commencez avec le mode restreint
      entries:
      - title: Mise en route du flux de travail
        url: "/task-quick-start-restricted-mode.html"
      - title: Préparation du déploiement
        url: "/task-prepare-restricted-mode.html"
      - title: Déployez le connecteur
        url: "/task-install-restricted-mode.html"
      - title: Abonnez-vous à BlueXP
        url: "/task-subscribe-restricted-mode.html"
      - title: Que pouvez-vous faire ensuite
        url: "/reference-whats-next-restricted-mode.html"
    - title: Commencez en mode privé
      entries:
      - title: Mise en route du flux de travail
        url: "/task-quick-start-private-mode.html"
      - title: Préparation du déploiement
        url: "/task-prepare-private-mode.html"
      - title: Déployez le connecteur
        url: "/task-install-private-mode.html"
      - title: Que pouvez-vous faire ensuite
        url: "/reference-whats-next-private-mode.html"
    - title: Connectez-vous à BlueXP
      url: "/task-logging-in.html"
  - title: Administration de BlueXP
    entries:
    - title: fédération des identités
      url: "/concept-federation.html"
    - title: Comptes BlueXP
      entries:
      - title: Gestion de votre compte BlueXP
        url: "/task-managing-netapp-accounts.html"
      - title: Contrôlez les opérations dans votre compte
        url: "/task-monitor-cm-operations.html"
      - title: Créez un autre compte BlueXP
        url: "/task-create-account.html"
      - title: Rôles utilisateur
        url: "/reference-user-roles.html"
    - title: Connecteurs
      entries:
      - title: Recherchez l'ID système d'un connecteur
        url: "/task-finding-system-id.html"
      - title: Gérer les connecteurs existants
        url: "/task-managing-connectors.html"
      - title: Installez un certificat HTTPS pour un accès sécurisé
        url: "/task-installing-https-cert.html"
      - title: Configurez un connecteur pour utiliser un serveur proxy
        url: "/task-configuring-proxy.html"
      - title: Configuration par défaut du connecteur
        url: "/reference-connector-default-config.html"
    - title: Informations d'identification et abonnements
      entries:
      - title: AWS
        entries:
        - title: En savoir plus sur les informations d'identification et les autorisations
          url: "/concept-accounts-aws.html"
        - title: Gérez les identifiants et les abonnements
          url: "/task-adding-aws-accounts.html"
      - title: Azure
        entries:
        - title: En savoir plus sur les informations d'identification et les autorisations
          url: "/concept-accounts-azure.html"
        - title: Gérez les identifiants et les abonnements
          url: "/task-adding-azure-accounts.html"
      - title: Google Cloud
        entries:
        - title: Apprenez-en plus sur les projets et les autorisations
          url: "/concept-accounts-gcp.html"
        - title: Gérez les identifiants et les abonnements
          url: "/task-adding-gcp-accounts.html"
      - title: Gérez les identifiants NSS associés à un compte BlueXP
        url: "/task-adding-nss-accounts.html"
      - title: Gestion des identifiants associés à votre connexion BlueXP
        url: "/task-manage-user-credentials.html"
    - title: Stockage cloud découvert
      entries:
      - title: Gestion de vos compartiments Amazon S3
        url: "/task-viewing-amazon-s3.html"
      - title: Gérez vos comptes Azure Blob
        url: "/task-viewing-azure-blob.html"
      - title: Gérez vos compartiments de stockage Google Cloud
        url: "/task-viewing-gcp-storage.html"
  - title: Référence
    entries:
    - title: Autorisations
      entries:
      - title: Résumé des autorisations
        url: "/reference-permissions.html"
      - title: Autorisations AWS pour le connecteur
        url: "/reference-permissions-aws.html"
      - title: Autorisations Azure pour le connecteur
        url: "/reference-permissions-azure.html"
      - title: Autorisations Google Cloud pour le connecteur
        url: "/reference-permissions-gcp.html"
    - title: Ports
      entries:
      - title: Règles du groupe de sécurité du connecteur dans AWS
        url: "/reference-ports-aws.html"
      - title: Règles du groupe de sécurité du connecteur dans Azure
        url: "/reference-ports-azure.html"
      - title: Règles de pare-feu du connecteur dans Google Cloud
        url: "/reference-ports-gcp.html"
      - title: Ports pour le connecteur sur site
        url: "/reference-ports-on-prem.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenez de l'aide
      url: "/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Commencez
    links:
    - title: En savoir plus sur BlueXP
      url: concept-overview.html
    - title: Découvrez les modes de déploiement
      url: concept-modes.html
    - title: Commencez avec le mode standard
      url: "/task-quick-start-standard-mode.html"
    - title: Commencez avec le mode restreint
      url: "/task-quick-start-restricted-mode.html"
    - title: Commencez en mode privé
      url: "/task-quick-start-private-mode.html"
  - title: Comptes BlueXP
    links:
    - title: Découvrez les comptes BlueXP
      url: concept-netapp-accounts.html
    - title: Gestion de votre compte BlueXP
      url: task-managing-netapp-accounts.html
    - title: Contrôlez les opérations dans votre compte
      url: task-monitor-cm-operations.html
  - title: Connecteurs
    links:
    - title: En savoir plus sur les connecteurs
      url: concept-connectors.html
    - title: Gérer les connecteurs
      url: task-managing-connectors.html
    - title: Afficher les autorisations AWS
      url: reference-permissions-aws.html
    - title: Afficher les autorisations Azure
      url: reference-permissions-azure.html
    - title: Afficher les autorisations Google Cloud
      url: reference-permissions-gcp.html
  - title: AWS
    links:
    - title: Commencez dans une région AWS standard
      url: task-quick-start-standard-mode.html
    - title: Commencez dans une région AWS GovCloud
      url: task-quick-start-restricted-mode.html
    - title: Commencez avec AWS Secret ou Top Secret Cloud
      url: https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-getting-started-aws-c2s.html
    - title: Afficher les politiques IAM du connecteur
      url: reference-permissions-aws.html
    - title: Gérez les identifiants et les abonnements
      url: task-adding-aws-accounts.html
  - title: Azure
    links:
    - title: Commencez dans une région Azure standard
      url: task-quick-start-standard-mode.html
    - title: Commencez dans une région Azure Government
      url: task-quick-start-restricted-mode.html
    - title: Lancez-vous dans Azure IL6
      url: task-quick-start-private-mode.html
    - title: Afficher le rôle personnalisé du connecteur
      url: reference-permissions-azure.html
    - title: Gérez les identifiants et les abonnements
      url: task-adding-azure-accounts.html
  - title: Google Cloud
    links:
    - title: Commencez dans une région Google Cloud standard
      url: task-quick-start-standard-mode.html
    - title: Afficher le compte de service pour le connecteur
      url: reference-permissions-gcp.html
    - title: Gérez les identifiants et les abonnements
      url: task-adding-gcp-accounts.html
  - title: Sur site
    links:
    - title: Installer et configurer un connecteur en mode standard
      url: task-install-connector-on-prem.html
    - title: Installer et configurer un connecteur en mode privé
      url: task-quick-start-private-mode.html
  - title: Connexion
    links:
    - title: Connectez-vous à BlueXP
      url: task-logging-in.html
    - title: Utilisation de la fédération des identités avec BlueXP
      url: concept-federation.html
  - title: Blogs et communauté
    links:
    - title: Communauté NetApp
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Blog BlueXP
      url: https://bluexp.netapp.com/blog
    - title: Webinaires sur le cloud
      url: https://bluexp.netapp.com/events
product-family:
  name: BlueXP
  repo: bluexp-family
