---
settings:
  name: BlueXP setup and administration
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentation sur l'installation et l'administration de BlueXP
    url: "/index.html"
  - title: Notes de mise à jour
    entries:
    - title: Quoi de neuf
      url: "/whats-new.html"
    - title: Limites connues
      url: "/reference-limitations.html"
    - title: Modifications apportées aux systèmes d'exploitation Linux pris en charge
      url: "/reference-connector-operating-system-changes.html"
  - title: Commencez
    entries:
    - title: Découvrez les bases
      entries:
      - title: BlueXP
        url: "/concept-overview.html"
      - title: Connecteurs
        url: "/concept-connectors.html"
      - title: Modes de déploiement
        url: "/concept-modes.html"
    - title: Commencez avec le mode standard
      entries:
      - title: Mise en route du flux de travail
        url: "/task-quick-start-standard-mode.html"
      - title: Préparez la mise en réseau pour la console BlueXP 
        url: "/reference-networking-saas-console.html"
      - title: Inscrivez-vous à BlueXP
        url: "/task-sign-up-saas.html"
      - title: Créer un connecteur
        entries:
        - title: AWS
          entries:
          - title: Options d'installation du connecteur
            url: "/concept-install-options-aws.html"
          - title: Créez un connecteur depuis BlueXP
            url: "/task-install-connector-aws-bluexp.html"
          - title: Créez un connecteur à partir du Marketplace
            url: "/task-install-connector-aws-marketplace.html"
          - title: Installer manuellement le connecteur
            url: "/task-install-connector-aws-manual.html"
        - title: Azure
          entries:
          - title: Options d'installation du connecteur
            url: "/concept-install-options-azure.html"
          - title: Créez un connecteur depuis BlueXP
            url: "/task-install-connector-azure-bluexp.html"
          - title: Créez un connecteur à partir du Marketplace
            url: "/task-install-connector-azure-marketplace.html"
          - title: Installer manuellement le connecteur
            url: "/task-install-connector-azure-manual.html"
        - title: Google Cloud
          entries:
          - title: Options d'installation du connecteur
            url: "/concept-install-options-google.html"
          - title: Créez un connecteur à partir de BlueXP ou de gcloud
            url: "/task-install-connector-google-bluexp-gcloud.html"
          - title: Installer manuellement le connecteur
            url: "/task-install-connector-google-manual.html"
        - title: Sur site
          url: "/task-install-connector-on-prem.html"
      - title: Abonnez-vous à BlueXP
        url: "/task-subscribe-standard-mode.html"
      - title: Que pouvez-vous faire ensuite
        url: "/reference-whats-next.html"
    - title: Commencez avec le mode restreint
      entries:
      - title: Mise en route du flux de travail
        url: "/task-quick-start-restricted-mode.html"
      - title: Préparation du déploiement
        url: "/task-prepare-restricted-mode.html"
      - title: Déployez le connecteur
        url: "/task-install-restricted-mode.html"
      - title: Abonnez-vous à BlueXP
        url: "/task-subscribe-restricted-mode.html"
      - title: Que pouvez-vous faire ensuite
        url: "/reference-whats-next-restricted-mode.html"
    - title: Commencez en mode privé
      entries:
      - title: Mise en route du flux de travail
        url: "/task-quick-start-private-mode.html"
      - title: Préparation du déploiement
        url: "/task-prepare-private-mode.html"
      - title: Déployez le connecteur
        url: "/task-install-private-mode.html"
      - title: Comptes BlueXP
        entries:
        - title: En savoir plus sur les comptes
          url: "/concept-netapp-accounts.html"
        - title: Gestion de votre compte BlueXP
          url: "/task-managing-netapp-accounts.html"
      - title: Que pouvez-vous faire ensuite
        url: "/reference-whats-next-private-mode.html"
    - title: Connectez-vous à BlueXP
      url: "/task-logging-in.html"
  - title: Administration de BlueXP
    entries:
    - title: Gestion des identités et des accès
      entries:
      - title: En savoir plus sur BlueXP  IAM
        url: "/concept-identity-and-access-management.html"
      - title: Lancez-vous avec BlueXP  IAM
        url: "/task-iam-get-started.html"
      - title: Organisez vos ressources avec des dossiers et des projets
        url: "/task-iam-manage-folders-projects.html"
      - title: Ajoutez des membres et gérez leurs autorisations
        url: "/task-iam-manage-members-permissions.html"
      - title: Gérez votre hiérarchie de ressources
        url: "/task-iam-manage-resources.html"
      - title: Associer un connecteur à d'autres dossiers et projets
        url: "/task-iam-associate-connectors.html"
      - title: Basculer entre les organisations, les projets et les connecteurs
        url: "/task-iam-switch-organizations-projects.html"
      - title: ID d'organisation et de projet
        url: "/task-iam-rename-organization.html"
      - title: Surveiller ou auditer l'activité IAM
        url: "/task-iam-audit-actions-timeline.html"
      - title: Rôles d'accès BlueXP
        url: "/reference-iam-predefined-roles.html"
    - title: Comptes BlueXP  (mode privé uniquement)
      entries:
      - title: En savoir plus sur les comptes
        url: "/concept-netapp-accounts.html"
      - title: Gestion de votre compte BlueXP
        url: "/task-managing-netapp-accounts.html"
    - title: fédération des identités
      url: "/concept-federation.html"
    - title: Connecteurs
      entries:
      - title: Maintenance de la machine virtuelle et du système d'exploitation
        url: "/task-maintain-connectors.html"
      - title: Installez un certificat signé par une autorité de certification pour
          l'accès à la console Web
        url: "/task-installing-https-cert.html"
      - title: Configurez un connecteur pour utiliser un serveur proxy
        url: "/task-configuring-proxy.html"
      - title: Requièrent l'utilisation d'IMDSv2 sur les instances EC2
        url: "/task-require-imdsv2.html"
      - title: Gérer les mises à niveau des connecteurs
        url: "/task-upgrade-connector.html"
      - title: Utilisation de plusieurs connecteurs
        url: "/task-manage-multiple-connectors.html"
      - title: Dépanner le connecteur
        url: "/task-troubleshoot-connector.html"
      - title: Désinstallez et retirez le connecteur
        url: "/task-uninstall-connector.html"
      - title: Configuration par défaut
        url: "/reference-connector-default-config.html"
      - title: Appliquez les autorisations ONTAP dans BlueXP 
        url: "/task-ontap-access-connector.html"
    - title: Informations d'identification et abonnements
      entries:
      - title: AWS
        entries:
        - title: En savoir plus sur les informations d'identification et les autorisations
          url: "/concept-accounts-aws.html"
        - title: Gérez les identifiants et les abonnements
          url: "/task-adding-aws-accounts.html"
      - title: Azure
        entries:
        - title: En savoir plus sur les informations d'identification et les autorisations
          url: "/concept-accounts-azure.html"
        - title: Gérez les identifiants et les abonnements
          url: "/task-adding-azure-accounts.html"
      - title: Google Cloud
        entries:
        - title: Apprenez-en plus sur les projets et les autorisations
          url: "/concept-accounts-gcp.html"
        - title: Gérez les identifiants et les abonnements
          url: "/task-adding-gcp-accounts.html"
      - title: Gérez les informations d'identification NSS associées à une organisation
          ou un compte BlueXP 
        url: "/task-adding-nss-accounts.html"
      - title: Gestion des identifiants associés à votre connexion BlueXP
        url: "/task-manage-user-credentials.html"
    - title: Surveillez les opérations BlueXP 
      url: "/task-monitor-cm-operations.html"
  - title: Référence
    entries:
    - title: Autorisations
      entries:
      - title: Résumé des autorisations
        url: "/reference-permissions.html"
      - title: Autorisations AWS pour le connecteur
        url: "/reference-permissions-aws.html"
      - title: Autorisations Azure pour le connecteur
        url: "/reference-permissions-azure.html"
      - title: Autorisations Google Cloud pour le connecteur
        url: "/reference-permissions-gcp.html"
    - title: Ports
      entries:
      - title: Règles du groupe de sécurité du connecteur dans AWS
        url: "/reference-ports-aws.html"
      - title: Règles du groupe de sécurité du connecteur dans Azure
        url: "/reference-ports-azure.html"
      - title: Règles de pare-feu du connecteur dans Google Cloud
        url: "/reference-ports-gcp.html"
      - title: Ports pour le connecteur sur site
        url: "/reference-ports-on-prem.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenez de l'aide
      url: "/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
