---
sidebar: sidebar 
permalink: reference-iam-keystone-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, identity and access management, access roles, admin 
summary: La gestion des identités et des accès BlueXP fournit deux rôles Keystone que vous pouvez attribuer aux membres de votre organisation. 
---
= Rôles d'accès Keystone pour BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les rôles Keystone permettent d'accéder aux tableaux de bord Keystone et permettent aux utilisateurs de consulter et de gérer leur abonnement Keystone. Il existe deux rôles Keystone : administrateur Keystone et visualiseur Keystone. La principale différence entre les deux rôles est les mesures qu'ils peuvent prendre dans Keystone. Le rôle admin de Keystone est le seul rôle autorisé à créer des demandes de service ou à modifier des abonnements.

.Exemple de rôles Keystone dans BlueXP 
XYZ Corporation dispose de quatre ingénieurs de stockage de différents départements qui consultent les informations d'abonnement Keystone. Bien que tous ces utilisateurs aient besoin de contrôler l'abonnement Keystone, seul le responsable de l'équipe est autorisé à faire des demandes de service. Trois des membres de l'équipe reçoivent le rôle *Keystone Viewer*, tandis que le responsable de l'équipe reçoit le rôle *Keystone admin*, de sorte qu'il existe un point de contrôle sur les demandes de service pour l'entreprise.

Le tableau suivant indique les actions que chaque rôle Keystone peut effectuer.

[cols="40,20a,20a"]
|===
| Fonction et action | Administrateur Keystone | Visualiseur Keystone 


| Affichez les onglets suivants : abonnement, actifs, moniteur et Administration  a| 
Oui.
 a| 
Oui.



3+| *Page d'abonnement Keystone* : 


| Afficher les abonnements  a| 
Oui.
 a| 
Oui.



| Modifier ou renouveler des abonnements  a| 
Oui.
 a| 
Non



3+| *Page des ressources Keystone* : 


| Afficher les ressources  a| 
Oui.
 a| 
Oui.



| Gérer les actifs  a| 
Oui.
 a| 
Non



3+| *Page d'alertes Keystone* : 


| Afficher les alertes  a| 
Oui.
 a| 
Non



| Gérer les alertes  a| 
Oui.
 a| 
Non



| Créez des alertes pour vous-même  a| 
Oui.
 a| 
Oui.



3+| *Porte-monnaie numérique* : 


| Peut afficher le portefeuille digital  a| 
Oui.
 a| 
Oui.



3+| *Page des rapports Keystone* : 


| Télécharger des rapports  a| 
Oui.
 a| 
Oui.



| Gérer les rapports  a| 
Oui.
 a| 
Oui.



| Créez des rapports pour vous-même  a| 
Oui.
 a| 
Oui.



3+| *Demandes de service* : 


| Créer des demandes de service  a| 
Oui.
 a| 
Non



| Afficher les demandes de service créées par n'importe quel utilisateur au sein de l'organisation  a| 
Oui.
 a| 
Oui.

|===