---
sidebar: sidebar 
permalink: reference-ports-azure.html 
keywords: ports, security group, http, https, inbound, outbound 
summary: 'Le groupe de sécurité Azure pour le connecteur nécessite à la fois des règles entrantes et sortantes. BlueXP crée automatiquement ce groupe de sécurité lorsque vous créez un connecteur à partir de BlueXP. Vous devez configurer ce groupe de sécurité pour toutes les autres options d"installation.' 
---
= Règles de groupe de sécurité dans Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le groupe de sécurité Azure pour le connecteur nécessite à la fois des règles entrantes et sortantes. BlueXP crée automatiquement ce groupe de sécurité lorsque vous créez un connecteur à partir de BlueXP. Vous devez configurer ce groupe de sécurité pour toutes les autres options d'installation.



== Règles entrantes

[cols="3*"]
|===
| Protocole | Port | Objectif 


| SSH | 22 | Fournit un accès SSH à l'hôte du connecteur 


| HTTP | 80 | Fournit un accès HTTP à partir des navigateurs Web du client vers l'interface utilisateur locale 


| HTTPS | 443 | Fournit un accès HTTPS à l'interface utilisateur locale depuis les navigateurs Web client et des connexions à partir de l'instance de classification BlueXP 


| TCP | 3128 | Permet à Cloud Volumes ONTAP d'accéder à Internet pour l'envoi des messages AutoSupport au support NetApp. Vous devez ouvrir ce port manuellement après le déploiement. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-verify-autosupport.html["Découvrez comment le connecteur est utilisé comme proxy pour les messages AutoSupport"^] 


| TCP | 9060 février 9061 | Permet d'activer et d'utiliser la classification BlueXP ainsi que la sauvegarde et la restauration BlueXP dans les régions du gouvernement. 
|===


== Règles de sortie

Le groupe de sécurité prédéfini pour le connecteur ouvre tout le trafic sortant. Si cela est acceptable, suivez les règles de base de l'appel sortant. Si vous avez besoin de règles plus rigides, utilisez les règles de sortie avancées.



=== Règles de base pour les appels sortants

Le groupe de sécurité prédéfini pour le connecteur inclut les règles de trafic sortant suivantes.

[cols="3*"]
|===
| Protocole | Port | Objectif 


| Tous les protocoles TCP | Tout | Tout le trafic sortant 


| Tous UDP | Tout | Tout le trafic sortant 
|===


=== Règles de sortie avancées

Si vous avez besoin de règles rigides pour le trafic sortant, vous pouvez utiliser les informations suivantes pour ouvrir uniquement les ports requis pour la communication sortante par le connecteur.


NOTE: L'adresse IP source est l'hôte du connecteur.

[cols="5*"]
|===
| Service | Protocole | Port | Destination | Objectif 


| Appels API et AutoSupport | HTTPS | 443 | LIF de gestion de cluster ONTAP et Internet sortant | Appels d'API vers Azure, vers ONTAP, vers la classification BlueXP et envoi de messages AutoSupport à NetApp 


| Appels API | TCP | 8080 | Classification BlueXP | Sonde à instance de classification BlueXP pendant le déploiement 


| DNS | UDP | 53 | DNS | Utilisé pour la résolution DNS par BlueXP 
|===