---
sidebar: sidebar 
permalink: reference-host-requirements-on-prem.html 
keywords: cpu requirements, ram requirements, on prem requirements, on prem host requirements, connector host requirements 
summary: 'Le logiciel du connecteur doit être exécuté sur un hôte qui répond à des exigences spécifiques du système d"exploitation, de la RAM, des ports, etc.' 
---
= Passez en revue la configuration requise pour les hôtes de connecteur pour les installations sur site
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le logiciel du connecteur doit être exécuté sur un hôte qui répond à des exigences spécifiques du système d'exploitation, de la RAM, des ports, etc.

Hôte dédié:: Le connecteur n'est pas pris en charge sur un hôte partagé avec d'autres applications. L'hôte doit être un hôte dédié.
Systèmes d'exploitation pris en charge::
+
--
* CentOS 7.6, 7.7, 7.8 et 7.9
* Red Hat Enterprise Linux 7.6, 7.7, 7.8, 7.9, 8.6 et 8.7
+
L'hôte doit être enregistré auprès de Red Hat Subscription Management. S'il n'est pas enregistré, l'hôte ne peut pas accéder aux référentiels pour mettre à jour les logiciels tiers requis lors de l'installation du connecteur.

+
Le connecteur est pris en charge sur les versions en anglais de ces systèmes d'exploitation.



--
Hyperviseur:: Un hyperviseur bare Metal ou hébergé certifié pour exécuter CentOS ou Red Hat Enterprise Linux est requis. https://access.redhat.com/certified-hypervisors["Solution Red Hat : quels hyperviseurs sont certifiés pour l'exécution de Red Hat Enterprise Linux ?"^]
CPU:: 4 cœurs ou 4 CPU virtuels
RAM:: 14 GO
Espace disque dans /opt:: 100 Gio d'espace doit être disponible
Espace disque dans /var:: 20 Gio d'espace doit être disponible
Moteur Docker:: Docker Engine version 19.3.1 ou ultérieure est requis sur l'hôte avant d'installer le connecteur. https://docs.docker.com/engine/install/["Voir les instructions d'installation"^]

