---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking 
summary: 'Lorsque vous utilisez la console web BlueXP fournie via la couche SaaS, il contacte plusieurs terminaux lorsqu"il effectue quelques tâches d"administration. Les ordinateurs qui accèdent à la console BlueXP doivent avoir des connexions à ces terminaux.' 
---
= Préparez la mise en réseau à l'aide de la console BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lorsque vous utilisez la console web BlueXP fournie via la couche SaaS, il contacte plusieurs terminaux lorsqu'il effectue quelques tâches d'administration. Les ordinateurs qui accèdent à la console BlueXP doivent avoir des connexions à ces terminaux.

Ces terminaux sont contactés depuis l'ordinateur d'un utilisateur lorsqu'ils effectuent des actions spécifiques à partir de la console BlueXP. Vous devez également consulter les exigences réseau pour le connecteur et pour des services BlueXP spécifiques. Pour plus de détails, reportez-vous aux liens connexes à la fin de cette page.

[cols="2*"]
|===
| Terminaux | Objectif 


| \https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com | Votre navigateur web contacte ces URL lorsque vous utilisez la console web BlueXP. 


 a| 
Services AWS (amazonaws.com):

* CloudFormation
* Cloud de calcul élastique (EC2)
* Service de gestion des clés (KMS)
* Service de jetons de sécurité (STS)
* Service de stockage simple (S3)

| Nécessaire pour déployer un connecteur depuis BlueXP dans AWS. Le point final exact dépend de la région dans laquelle vous déployez le connecteur. https://docs.aws.amazon.com/general/latest/gr/rande.html["Reportez-vous à la documentation AWS pour plus de détails."^] 


| \https://management.azure.com

\https://login.microsoftonline.com | Nécessaire au déploiement d'un connecteur depuis BlueXP dans la plupart des régions Azure. 


| \https://management.microsoftazure.de

\https://login.microsoftonline.de | Nécessaire au déploiement d'un connecteur depuis BlueXP dans les régions d'Azure Allemagne. 


| \https://management.usgovcloudapi.net

\https://login.microsoftonline.com | Nécessaire au déploiement d'un connecteur de BlueXP dans les régions Azure Government. 


| \https://www.googleapis.com | Nécessaire pour déployer un connecteur depuis BlueXP dans Google Cloud. 


| \https://signin.b2c.netapp.com | Requis pour mettre à jour les identifiants du site de support NetApp (NSS) ou pour ajouter de nouvelles informations d'identification NSS à BlueXP. 


| \https://netapp-cloud-account.auth0.com

\https://cdn.auth0.com

\https://services.cloud.netapp.com | Votre navigateur Web se connecte à ces points de terminaison pour une authentification utilisateur centralisée via BlueXP. 


| \https://widget.intercom.io | Vous bénéficiez d'un chat en ligne pour discuter avec des experts du cloud NetApp. 
|===
Au-delà de ces terminaux, vous devez également vous assurer que le connecteur dispose d'un accès Internet sortant pour contacter des terminaux spécifiques pour les opérations quotidiennes. Vous trouverez la liste de ces points d'extrémité en suivant les liens de la section suivante ci-dessous.

.Liens connexes
* Préparez la mise en réseau pour le connecteur
+
** link:task-install-connector-aws-bluexp.html#step-1-set-up-networking["Configuration du réseau AWS"]
** link:task-install-connector-azure-bluexp.html#step-1-set-up-networking["Configuration du réseau Azure"]
** link:task-install-connector-google-bluexp-gcloud.html#step-1-set-up-networking["Configuration du réseau Google Cloud"]
** link:task-install-connector-on-prem.html#step-2-set-up-networking["Configuration du réseau sur site"]


* Préparez la mise en réseau pour les services BlueXP
+
Consultez la documentation de chaque service BlueXP.

+
https://docs.netapp.com/us-en/bluexp-family/["Documentation BlueXP"^]


