---
sidebar: sidebar 
permalink: reference-iam-predefined-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: La gestion des identités et des accès BlueXP  inclut plusieurs rôles prédéfinis que vous pouvez attribuer aux membres de votre organisation. 
---
= Rôles et autorisations BlueXP  IAM prédéfinis
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La gestion des identités et des accès BlueXP  inclut plusieurs rôles prédéfinis que vous pouvez attribuer aux membres de votre entreprise à différents niveaux de votre hiérarchie de ressources. Avant d'attribuer ces rôles, vous devez comprendre les autorisations incluses par chaque rôle.



== Rôles de plateforme

L'IAM BlueXP  comprend deux rôles de plateforme : administrateur d'organisation et administrateur de dossiers ou de projets. La principale différence entre les deux rôles de plateforme BlueXP  IAM est le périmètre. Le rôle d'administrateur d'organisation a des autorisations dans tous les dossiers et projets, tandis que l'administrateur de dossier ou de projet n'a que des autorisations dans le dossier ou le projet auquel ils ont été affectés.

Le rôle d'administrateur dossier ou projet ne peut pas créer de connecteurs.

Autorisations::


[cols="24,19,19"]
|===
| Tâche | Administrateur d'entreprise | Administrateur de dossier ou de projet 


| Créer des connecteurs | Oui. | Non 


| Créer, modifier ou supprimer des environnements de travail (ajouter ou découvrir de nouvelles ressources à l'aide du canevas BlueXP ) | Oui. | Oui. 


| Créer des projets/dossiers, notamment renommer, supprimer et modifier | Oui. | Oui. 


| Attribuez des rôles et ajoutez des utilisateurs | Oui. | Oui. 


| Associer des ressources et des connecteurs aux dossiers et projets | Oui. | Oui. 


| Gérez les informations d'identification dans Paramètres > informations d'identification | Oui. | Oui. 


| Afficher la chronologie BlueXP  | Oui. | Oui. 


| Utilisez les services BlueXP  | Oui. | Oui. 


| Enregistrez BlueXP  pour obtenir de l'aide et envoyez vos dossiers de demande de support | Oui. | Oui. 
|===
Exemple de rôles d'organisation au BlueXP  pour une grande organisation multinationale:: XYZ Corporation, une multinationale, a pour objectif de séparer l'accès aux ressources de stockage des données en fonction de régions géographiques : Amérique du Nord, Europe et Asie-Pacifique. Ils veulent que chaque région dispose d'un contrôle exclusif sur leurs ressources tout en maintenant une surveillance centralisée.
+
--
Pour ce faire, une personne affectée au rôle d'administrateur d'organisation dans BlueXP  de la société XYZ crée un environnement de travail initial, puis crée des dossiers distincts dans BlueXP  pour chaque région. Le dossier de chaque région contient des projets (avec des ressources associées) liés à cette région. L'administrateur de l'organisation attribue à un utilisateur BlueXP  dans chaque région respective le rôle d'administrateur dossier/projet.

Une fois la configuration initiale terminée, les administrateurs régionaux dotés du rôle d'administrateur de dossier ou de projet peuvent créer de nouveaux environnements de travail et ajouter des utilisateurs au sein de leur région. Ces administrateurs régionaux peuvent également ajouter/supprimer/renommer des dossiers et des projets auxquels ils sont affectés. L'administrateur de l'entreprise hérite des autorisations de tous les nouveaux environnements de travail ou ressources, ce qui permet de maintenir une visibilité sur l'utilisation du stockage dans toute l'entreprise.

--




== Rôles liés aux services de données

Les rôles de services de données peuvent effectuer leurs tâches dans n'importe quel projet ou dossier.



=== Administrateur SnapCenter

Description:: Permet de sauvegarder des copies Snapshot à partir de clusters ONTAP sur site à l'aide de la sauvegarde et de la restauration BlueXP  pour les applications.
Autorisations:: Un membre qui a ce rôle peut effectuer les actions suivantes dans BlueXP  :
+
--
* Effectuez toutes les opérations à partir de la commande sauvegarde et restauration > applications
* Gérez tous les environnements de travail dans les projets et dossiers pour lesquels ils ont des autorisations
* Utilisation de tous les services BlueXP 


--




=== Visualiseur de classification

Description:: Fournit la possibilité d'afficher les résultats de l'acquisition de classification BlueXP .
Autorisations:: Affichez les informations de conformité et générez des rapports pour les ressources auxquelles ils ont accès. Ces utilisateurs ne peuvent ni activer ni désactiver l'analyse de volumes, de compartiments ou de schémas de base de données.
+
--
Aucune autre action n'est disponible pour un membre qui a ce rôle.

--




== Liens connexes

* link:concept-identity-and-access-management.html["En savoir plus sur la gestion des identités et des accès BlueXP "]
* link:task-iam-get-started.html["Lancez-vous avec BlueXP  IAM"]
* link:task-iam-manage-members-permissions.html["Gérez les membres BlueXP  et leurs autorisations"]
* https://docs.netapp.com/us-en/bluexp-automation/tenancyv4/overview.html["En savoir plus sur l'API pour BlueXP  IAM"^]

