---
sidebar: sidebar 
permalink: reference-iam-platform-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: Attribuez des rôles de plateforme aux utilisateurs pour accorder des autorisations pour gérer BlueXP, attribuer des rôles, ajouter des utilisateurs, créer des connecteurs et gérer les fédérations. 
---
= Rôles d'accès à la plateforme BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Attribuez des rôles de plateforme aux utilisateurs pour accorder des autorisations pour gérer BlueXP, attribuer des rôles, ajouter des utilisateurs, créer des connecteurs et gérer les fédérations.

.Exemple de rôles d'organisation au BlueXP  pour une grande organisation multinationale
XYZ Corporation organise l'accès au stockage des données par région (Amérique du Nord, Europe et Asie-Pacifique), donnant à chaque région le contrôle tout en garantissant une surveillance centralisée.

L'*administrateur de l'organisation* dans BlueXP de la société XYZ crée une organisation initiale et des dossiers distincts pour chaque région. Le dossier de chaque région contient des projets (avec des ressources associées) liés à cette région. Le *administrateur de l'organisation* attribue à un utilisateur BlueXP  dans chaque région respective le rôle *administrateur du dossier ou du projet*.

Les administrateurs régionaux dotés du rôle *Administrateur de dossier ou de projet* gèrent leurs régions (dossiers) en ajoutant de nouvelles ressources et de nouveaux utilisateurs. Ils peuvent également ajouter, supprimer ou renommer les dossiers et les projets qu'ils gèrent. L'*Administrateur d'organisation* hérite des autorisations pour toute nouvelle ressource, garantissant ainsi une visibilité sur l'utilisation du stockage dans toute l'organisation.

Au sein d'une même organisation, un utilisateur se voit attribuer le rôle d'administrateur de la fédération pour gérer la fédération avec son fournisseur d'identité d'entreprise. Cet utilisateur peut ajouter ou supprimer des organisations fédérées, mais ne peut pas gérer les utilisateurs ni les ressources de l'organisation. L'organisation attribue à un utilisateur le rôle de visualiseur de la fédération pour vérifier l'état de la fédération et visualiser les organisations fédérées sans effectuer de modifications.

Les tableaux suivants indiquent les actions que chaque rôle de la plateforme BlueXP peut effectuer.



== Rôles d'administration de l'organisation

[cols="2,1,1"]
|===
| Tâche | Administrateur d'entreprise | Administrateur de dossiers ou de projets 


| Créer des connecteurs | Oui. | Non 


| Créer, modifier ou supprimer des environnements de travail (ajouter ou découvrir de nouvelles ressources à l'aide du canevas BlueXP ) | Oui. | Oui. 


| Créer des dossiers et des projets, y compris la suppression | Oui. | Non 


| Renommer les dossiers et projets existants | Oui. | Oui. 


| Attribuez des rôles et ajoutez des utilisateurs | Oui. | Oui. 


| Associer des ressources à des dossiers et des projets | Oui. | Oui. 


| Associer des connecteurs à des dossiers et des projets | Oui. | Non 


| Supprimer des connecteurs d'un dossier et d'un projet | Oui. | Non 


| Gérer les connecteurs (modifier les certificats, les paramètres, etc.) | Oui. | Non 


| Gérez les informations d'identification dans Paramètres > informations d'identification | Oui. | Oui. 


| Créer, gérer et visualiser les fédérations | Oui. | Non 


| Inscrivez-vous pour obtenir de l'aide et soumettre des cas | Oui. | Oui. 


| Utiliser les services de données | Oui. | Oui. 


| Afficher la chronologie et les notifications BlueXP | Oui. | Oui. 
|===


== Rôles de la Fédération

[cols="2,1,1"]
|===
| Tâche | Administrateur de la fédération | Téléspectateur de la Fédération 


| Créer une fédération | Oui. | Non 


| Vérifier un domaine | Oui. | Non 


| Ajouter un domaine à une fédération | Oui. | Non 


| Désactiver et supprimer les fédérations | Oui. | Non 


| Fédérations de tests | Oui. | Non 


| Voir les fédérations et leurs coordonnées | Oui. | Oui. 
|===