---
sidebar: sidebar 
permalink: reference-iam-predefined-roles.html 
keywords: predefined roles, access roles,  iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: La gestion des identités et des accès BlueXP  inclut plusieurs rôles prédéfinis que vous pouvez attribuer aux membres de votre organisation. 
---
= Rôles d'accès BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les rôles d'accès BlueXP  ont été conçus pour donner à un utilisateur les privilèges les plus faibles afin d'accomplir des tâches de gestion du stockage. Cela assure une sécurité accrue et empêche les utilisateurs d'interrompre par inadvertance les services de stockage lorsqu'ils ne disposent pas d'autorisations. Les rôles se divisent en trois catégories : plateforme, application et service de données.

Toute personne ayant un rôle de plate-forme BlueXP  (administrateur d'organisation ou administrateur de projet ou de dossier) peut ajouter un utilisateur à un projet et lui attribuer un rôle ou des rôles pour un projet ou un dossier particulier.



== Rôles de la plateforme BlueXP 

Les rôles de plateforme disposent d'autorisations complètes pour l'administration BlueXP , notamment l'attribution de rôles et l'ajout d'utilisateurs, ainsi que la possibilité d'exécuter toutes les fonctions de gestion BlueXP  pour les ressources de stockage et les services de données. BlueXP  inclut deux rôles au niveau de la plate-forme : administrateur d'organisation et administrateur de dossiers ou de projets.

.Exemple : utilisez des rôles de plate-forme pour déléguer des responsabilités administratives
XYZ Corporation, une multinationale, a pour objectif de séparer l'accès aux ressources de stockage des données en fonction de régions géographiques : Amérique du Nord, Europe et Asie-Pacifique. Ils veulent que chaque région dispose d'un contrôle exclusif sur leurs ressources tout en maintenant une surveillance centralisée.

Pour ce faire, une personne affectée au rôle d'administrateur d'organisation dans BlueXP  de la société XYZ crée un environnement de travail initial, puis crée des dossiers distincts dans BlueXP  pour chaque région. Le dossier de chaque région contient des projets (avec des ressources associées) liés à cette région. L'administrateur de l'organisation attribue à un utilisateur BlueXP  dans chaque région respective le rôle d'administrateur dossier/projet.

Une fois la configuration initiale terminée, les administrateurs régionaux dotés du rôle d'administrateur de dossier ou de projet peuvent créer de nouveaux environnements de travail et ajouter des utilisateurs au sein de leur région. Ces administrateurs régionaux peuvent également ajouter/supprimer/renommer des dossiers et des projets auxquels ils sont affectés. L'administrateur de l'entreprise hérite des autorisations de tous les nouveaux environnements de travail ou ressources, ce qui permet de maintenir une visibilité sur l'utilisation du stockage dans toute l'entreprise.

Les rôles de plate-forme suivants sont disponibles :

* *Organisation admin* : permet à un utilisateur d'accéder sans restriction à tous les projets et dossiers d'une organisation, d'ajouter des membres à n'importe quel projet ou dossier, ainsi que d'effectuer n'importe quelle tâche de gestion BlueXP  et d'utiliser n'importe quel service de données. Une organisation doit avoir au moins un administrateur d'organisation.
* *Dossier ou administrateur de projet* : permet à un utilisateur d'accéder sans restriction à des projets et dossiers spécifiques auxquels ils sont affectés. Vous pouvez ajouter des membres à des projets ou dossiers qu'ils gèrent, ainsi qu'effectuer n'importe quelle tâche de gestion BlueXP  et utiliser n'importe quel service de données dans le dossier ou le projet auquel ils sont affectés. Le rôle d'administrateur dossier ou projet ne peut pas créer de connecteurs.


Le tableau suivant indique les actions que chaque rôle de protection de plateforme BlueXP  peut effectuer.

[cols="24,19,19"]
|===
| Tâche | Administrateur d'entreprise | Administrateur de dossier ou de projet 


| Créer des connecteurs | Oui. | Non 


| Créer, modifier ou supprimer des environnements de travail (ajouter ou découvrir de nouvelles ressources à l'aide du canevas BlueXP ) | Oui. | Oui. 


| Créer des projets/dossiers, y compris la suppression | Oui. | Non 


| Renommer des projets/dossiers existants | Oui. | Oui. 


| Attribuez des rôles et ajoutez des utilisateurs | Oui. | Oui. 


| Associer des ressources à des dossiers et des projets | Oui. | Oui. 


| Associer des connecteurs à des dossiers et des projets | Oui. | Non 


| Supprimer des connecteurs d'un dossier et d'un projet | Oui. | Non 


| Gérer les connecteurs (modifier les certificats, les paramètres, etc.) | Oui. | Non 


| Gérez les informations d'identification dans Paramètres > informations d'identification | Oui. | Oui. 


| Afficher la chronologie BlueXP  | Oui. | Oui. 


| Utilisez les services BlueXP  | Oui. | Oui. 


| Enregistrez BlueXP  pour obtenir de l'aide et envoyez vos dossiers de demande de support | Oui. | Oui. 
|===


== Rôles d'application

Vous trouverez ci-dessous la liste des rôles dans la catégorie application.



=== Rôles Keystone

Vous pouvez affecter l'accès des utilisateurs à Keystone à l'aide des rôles suivants.


NOTE: L'accès à Keystone via BlueXP  est actuellement en version bêta. Si vous souhaitez participer à la version bêta de Keystone, contactez votre conseiller NetApp.

* *Keystone admin* : gérez l'abonnement Keystone et prenez des mesures concernant les alertes, les rapports et les abonnements.
* *Afficheur Keystone* : affichez l'abonnement Keystone ainsi que les rapports, alertes et ressources.


Le tableau suivant indique les actions que chaque rôle Keystone peut effectuer.

[cols="40,20a,20a"]
|===
| Fonction et action | Administrateur Keystone | Visualiseur Keystone 


| Affichez les onglets suivants : abonnement, actifs, moniteur et Administration  a| 
Oui.
 a| 
Oui.



3+| *Page d'abonnement Keystone* : 


| Permet d'afficher les abonnements  a| 
Oui.
 a| 
Oui.



| Peut modifier ou renouveler des abonnements  a| 
Oui.
 a| 
Non



3+| *Page des ressources Keystone* : 


| Afficher les ressources  a| 
Oui.
 a| 
Oui.



| Gérer les actifs  a| 
Oui.
 a| 
Non



3+| *Page d'alertes Keystone* : 


| Afficher les alertes  a| 
Oui.
 a| 
Non



| Gérer les alertes  a| 
Oui.
 a| 
Non



| Créez des alertes pour vous-même  a| 
Oui.
 a| 
Oui.



3+| *Porte-monnaie numérique* : 


| Peut afficher le portefeuille digital  a| 
Oui.
 a| 
Oui.



3+| *Page des rapports Keystone* : 


| Télécharger des rapports  a| 
Oui.
 a| 
Oui.



| Gérer les rapports  a| 
Oui.
 a| 
Oui.



| Créez des rapports pour vous-même  a| 
Oui.
 a| 
Oui.



3+| *Demandes de service* : 


| Créer des demandes de service  a| 
Oui.
 a| 
Non



| Peut voir la demande de service créée par n'importe quel utilisateur au sein de l'organisation  a| 
Oui.
 a| 
Oui.

|===


== Rôles liés aux services de données

Vous trouverez ci-dessous la liste des rôles dans la catégorie Services de données.



=== Visualiseur de classification

Fournit la possibilité d'afficher les résultats de l'acquisition de classification BlueXP .

La classification n'a pas de rôle d'administrateur.

Autorisations:: Affichez les informations de conformité et générez des rapports pour les ressources auxquelles ils ont accès. Ces utilisateurs ne peuvent ni activer ni désactiver l'analyse de volumes, de compartiments ou de schémas de base de données.


Aucune autre action n'est disponible pour un membre qui a ce rôle.



=== Protection par ransomware

Vous pouvez utiliser les rôles suivants pour attribuer aux utilisateurs l'accès à la protection contre les ransomwares.

* *Protection anti-ransomware admin* : gestion des actions dans les onglets protéger, alertes, récupérer, Paramètres et Rapports.
* *Visualiseur de protection contre les ransomware* : afficher les données de charge de travail, afficher les données d'alerte, télécharger les données de récupération et télécharger les rapports.


Le tableau suivant indique les actions que chaque rôle de protection contre les ransomwares BlueXP  peut effectuer.

[cols="40,20a,20a"]
|===
| Fonction et action | Administrateur de la protection contre les ransomwares | Visualiseur de protection contre les ransomware 


| Afficher le tableau de bord et tous les onglets  a| 
Oui.
 a| 
Oui.



| Essayer gratuitement  a| 
Oui.
 a| 
Non



| Lancez la découverte des charges de travail  a| 
Oui.
 a| 
Non



3+| *Sur l'onglet protéger* : 


| Ajoutez, modifiez ou supprimez des règles  a| 
Oui.
 a| 
Non



| Protégez les workloads  a| 
Oui.
 a| 
Non



| Identifiez les données sensibles  a| 
Oui.
 a| 
Non



| Modifier la protection des charges de travail  a| 
Oui.
 a| 
Non



| Afficher les détails de la charge de travail  a| 
Oui.
 a| 
Oui.



| Téléchargez les données  a| 
Oui.
 a| 
Oui.



3+| *Sur l'onglet alertes* : 


| Afficher les détails des alertes  a| 
Oui.
 a| 
Oui.



| Modifier l'état de l'incident  a| 
Oui.
 a| 
Non



| Afficher les détails de l'incident  a| 
Oui.
 a| 
Oui.



| Obtenir la liste complète des fichiers affectés  a| 
Oui.
 a| 
Non



| Télécharger les données d'alertes  a| 
Oui.
 a| 
Oui.



3+| *Sur l'onglet récupérer* : 


| Télécharger les fichiers impactés  a| 
Oui.
 a| 
Non



| Restaurer la charge de travail  a| 
Oui.
 a| 
Non



| Télécharger les données de récupération  a| 
Oui.
 a| 
Oui.



| Télécharger des rapports  a| 
Oui.
 a| 
Oui.



3+| *Sur l'onglet Paramètres* : 


| Ajouter ou modifier des cibles de sauvegarde  a| 
Oui.
 a| 
Non



| Ajouter ou modifier des cibles SIEM  a| 
Oui.
 a| 
Non



3+| *Sur l'onglet Rapports* : 


| Télécharger des rapports  a| 
Oui.
 a| 
Oui.

|===


=== Administrateur SnapCenter

Permet de sauvegarder des copies Snapshot à partir de clusters ONTAP sur site à l'aide de la sauvegarde et de la restauration BlueXP  pour les applications.

SnapCenter n'a pas de rôle de visualiseur.

Autorisations:: Un membre qui a ce rôle peut effectuer les actions suivantes dans BlueXP  :
+
--
* Effectuez toutes les opérations à partir de la commande sauvegarde et restauration > applications
* Gérez tous les environnements de travail dans les projets et dossiers pour lesquels ils ont des autorisations
* Utilisation de tous les services BlueXP 


--




== Liens connexes

* link:concept-identity-and-access-management.html["En savoir plus sur la gestion des identités et des accès BlueXP "]
* link:task-iam-get-started.html["Lancez-vous avec BlueXP  IAM"]
* link:task-iam-manage-members-permissions.html["Gérez les membres BlueXP  et leurs autorisations"]
* https://docs.netapp.com/us-en/bluexp-automation/tenancyv4/overview.html["En savoir plus sur l'API pour BlueXP  IAM"^]

