---
sidebar: sidebar 
permalink: reference-connector-maint-console.html 
keywords: transparent proxy, connector certificate, agent maintenance console, proxy configuration, connector proxy 
summary: Utilisez la console de maintenance pour configurer le connecteur afin d’utiliser un serveur proxy transparent. 
---
= Console de maintenance des connecteurs
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez utiliser la console de maintenance pour configurer le connecteur afin d’utiliser un serveur proxy transparent.



== Accéder à la Console de maintenance

Vous pouvez accéder à la console de maintenance à partir de l’hôte du connecteur. Accédez au répertoire suivant :

[source, CLI]
----
/opt/application/netapp/service-manager-2/connector-maint-console
----


== Commandes proxy transparentes

La console de maintenance fournit des commandes pour configurer le connecteur afin d'utiliser un serveur proxy transparent.



=== Afficher la configuration actuelle du proxy transparent

Pour afficher la configuration actuelle du proxy transparent, utilisez la commande suivante :

[source, CLI]
----
./connector-maint-console proxy get
----


=== Ajouter un serveur proxy transparent

Pour ajouter un serveur proxy transparent, utilisez la commande suivante, où  `/home/ubuntu/myCA1.pem` est le chemin d'accès au fichier de certificat du serveur proxy. Le fichier de certificat doit être au format PEM :

[source, CLI]
----
./connector-maint-console proxy add -c /home/ubuntu/myCA1.pem
----
Assurez-vous que le fichier de certificat se trouve dans le même répertoire que la commande ou spécifiez le chemin d’accès complet au fichier de certificat.



=== Mettre à jour le certificat pour un serveur proxy transparent

Pour mettre à jour le certificat d'un serveur proxy transparent, utilisez la commande suivante, où  `/home/ubuntu/myCA1.pem` est le chemin d'accès au nouveau fichier de certificat du serveur proxy. Le fichier de certificat doit être au format PEM :

[source, CLI]
----
./connector-maint-console proxy update -c /home/ubuntu/myCA1.pem
----
Assurez-vous que le fichier de certificat se trouve dans le même répertoire que la commande ou spécifiez le chemin d’accès complet au fichier de certificat.



=== Supprimer un serveur proxy transparent

Pour supprimer le serveur proxy transparent, utilisez la commande suivante :

[source, CLI]
----
./connector-maint-console proxy remove
----


=== Afficher l'aide pour n'importe quelle commande

Pour afficher l'aide d'une commande, ajoutez  `--help` à la commande. Par exemple, pour afficher l'aide relative à  `proxy add` commande, utilisez la commande suivante :

[source, CLI]
----
./connector-maint-console proxy add --help
----