---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking 
summary: 'Lorsque vous démarrez avec BlueXP, assurez-vous que votre réseau permet d"accéder à des terminaux spécifiques à partir de la console BlueXP. Selon votre mode d"utilisation de BlueXP, vous devrez peut-être également configurer une mise en réseau pour un connecteur et pour des services BlueXP spécifiques.' 
---
= Préparez votre réseau
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lorsque vous démarrez avec BlueXP, assurez-vous que votre réseau permet d'accéder à des terminaux spécifiques à partir de la console BlueXP. Selon votre mode d'utilisation de BlueXP, vous devrez peut-être également configurer une mise en réseau pour un connecteur et pour des services BlueXP spécifiques.



== Préparez la mise en réseau pour l'accès utilisateur à la console BlueXP

Lorsque vous utilisez la console web BlueXP fournie via la couche SaaS, elle contacte plusieurs terminaux pour effectuer les tâches de gestion des données. La machine exécutant le navigateur Web doit avoir des connexions à ces noeuds finaux.

[cols="2*"]
|===
| Terminaux | Objectif 


| \https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com | Votre navigateur web contacte ces URL lorsque vous utilisez la console web BlueXP. 


 a| 
Services AWS (amazonaws.com):

* CloudFormation
* Cloud de calcul élastique (EC2)
* Service de gestion des clés (KMS)
* Service de jetons de sécurité (STS)
* Service de stockage simple (S3)

| Nécessaire pour déployer un connecteur depuis BlueXP dans AWS. Le point final exact dépend de la région dans laquelle vous déployez le connecteur. https://docs.aws.amazon.com/general/latest/gr/rande.html["Reportez-vous à la documentation AWS pour plus de détails."^] 


| \https://management.azure.com

\https://login.microsoftonline.com | Nécessaire au déploiement d'un connecteur depuis BlueXP dans la plupart des régions Azure. 


| \https://management.microsoftazure.de

\https://login.microsoftonline.de | Nécessaire au déploiement d'un connecteur depuis BlueXP dans les régions d'Azure Allemagne. 


| \https://management.usgovcloudapi.net

\https://login.microsoftonline.com | Nécessaire au déploiement d'un connecteur de BlueXP dans les régions Azure Government. 


| \https://www.googleapis.com | Nécessaire pour déployer un connecteur depuis BlueXP dans Google Cloud. 


| \https://signin.b2c.netapp.com | Requis pour mettre à jour les identifiants du site de support NetApp (NSS) ou pour ajouter de nouvelles informations d'identification NSS à BlueXP. 


| \https://netapp-cloud-account.auth0.com

\https://cdn.auth0.com

\https://services.cloud.netapp.com | Votre navigateur Web se connecte à ces points de terminaison pour une authentification utilisateur centralisée via BlueXP. 


| \https://widget.intercom.io | Vous bénéficiez d'un chat en ligne pour discuter avec des experts du cloud NetApp. 
|===
Au-delà de ces terminaux, vous devez également vous assurer que le connecteur dispose d'un accès Internet sortant pour contacter des terminaux spécifiques pour les opérations quotidiennes. Vous trouverez la liste de ces points d'extrémité en suivant les liens de la section suivante ci-dessous.



== Préparez la mise en réseau d'un connecteur

La manière dont vous préparez votre mise en réseau pour un connecteur dépend de l'endroit où vous prévoyez d'installer le connecteur, qui peut se trouver dans le cloud ou sur site. Pour plus d'informations sur les exigences de mise en réseau des connecteurs, reportez-vous aux pages suivantes :

* link:task-set-up-networking-aws.html["Configuration du réseau AWS"]
* link:task-set-up-networking-azure.html["Configuration du réseau Azure"]
* link:task-set-up-networking-google.html["Configuration du réseau Google Cloud"]
* link:task-set-up-networking-on-prem.html["Configuration du réseau sur site"]




== Préparez la mise en réseau pour les services BlueXP

Lorsque vous commencez à utiliser BlueXP, vous devez vous assurer que vous répondez aux exigences de mise en réseau des services BlueXP que vous prévoyez d'utiliser. Pour plus de détails, reportez-vous à la documentation de chaque service.

https://docs.netapp.com/us-en/bluexp-family/["Documentation BlueXP"^]
