---
sidebar: sidebar 
permalink: reference-iam-predefined-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: La gestion des identités et des accès BlueXP  inclut plusieurs rôles prédéfinis que vous pouvez attribuer aux membres de votre organisation. 
---
= Rôles et autorisations BlueXP  IAM prédéfinis
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La gestion des identités et des accès BlueXP  inclut plusieurs rôles prédéfinis que vous pouvez attribuer aux membres de votre entreprise à différents niveaux de votre hiérarchie de ressources. Avant d'attribuer ces rôles, vous devez comprendre les autorisations incluses par chaque rôle.



== Administrateur d'entreprise

Description:: Contrôle total de l'ensemble de l'organisation BlueXP .
Autorisations:: Un membre qui a ce rôle peut effectuer toutes les actions dans BlueXP .




== Administrateur de dossiers ou de projets

Description:: Permet un contrôle total d'un ou de plusieurs projets et dossiers.
+
--
Notez que si vous attribuez ce rôle au niveau du dossier, le membre dispose d'autorisations sur tous les projets associés à ce dossier.

--
Autorisations:: Un membre qui a ce rôle peut effectuer les actions suivantes dans BlueXP  :
+
--
* Gérez tous les environnements de travail dans les projets et dossiers pour lesquels ils ont des autorisations
* Utilisation de tous les services BlueXP 
* Depuis BlueXP  IAM, l'administrateur d'un dossier peut gérer les dossiers, les projets et les ressources enfants de ce dossier :
+
** Ajoutez des dossiers ou des projets dans le dossier
** Modifier les dossiers et les projets : leurs noms, les ressources associées et l'accès aux membres
** Supprimer des dossiers et des projets
** Ajoutez un compte utilisateur et associez un rôle au niveau du dossier ou du projet
** Associer un connecteur à un dossier ou un projet
** Ajoutez un rôle à un membre au niveau du dossier ou du projet
** Afficher les ressources associées aux dossiers et aux projets
** Associer des ressources visibles à des dossiers ou projets supplémentaires
** Dissocier une ressource d'un dossier ou d'un projet


* Depuis BlueXP  IAM, l'administrateur d'un projet peut gérer ce projet et ses ressources associées comme suit :
+
** Modifiez le projet : son nom, les ressources associées et l'accès aux membres
** Ajoutez un compte utilisateur et associez un rôle au niveau du projet
** Associez un connecteur à un projet, si le membre a des autorisations d'administration sur d'autres projets qui ont d'autres connecteurs associés
** Ajoutez un rôle à un membre au niveau du projet
** Afficher les ressources associées au projet
** Associez des ressources au projet, si le membre dispose d'autorisations d'administration sur d'autres projets qui ont d'autres ressources associées
** Dissocier une ressource du projet
** Supprimez le projet


* Gérez les informations d'identification dans Paramètres > informations d'identification
* Afficher la chronologie BlueXP 
* Enregistrez BlueXP  pour obtenir de l'aide et envoyez vos dossiers de demande de support


--




== Administrateur SnapCenter

Description:: Permet de sauvegarder des copies Snapshot à partir de clusters ONTAP sur site à l'aide de la sauvegarde et de la restauration BlueXP  pour les applications.
Autorisations:: Un membre qui a ce rôle peut effectuer les actions suivantes dans BlueXP  :
+
--
* Effectuez toutes les opérations à partir de la commande sauvegarde et restauration > applications
* Gérez tous les environnements de travail dans les projets et dossiers pour lesquels ils ont des autorisations
* Utilisation de tous les services BlueXP 


--




== Visualiseur de classification

Description:: Fournit la possibilité d'afficher les résultats de l'acquisition de classification BlueXP .
Autorisations:: Affichez les informations de conformité et générez des rapports pour les ressources auxquelles ils ont accès. Ces utilisateurs ne peuvent ni activer ni désactiver l'analyse de volumes, de compartiments ou de schémas de base de données.
+
--
Aucune autre action n'est disponible pour un membre qui a ce rôle.

--




== Liens connexes

* link:concept-identity-and-access-management.html["En savoir plus sur la gestion des identités et des accès BlueXP "]
* link:task-iam-get-started.html["Lancez-vous avec BlueXP  IAM"]
* link:task-iam-manage-members-permissions.html["Gérez les membres BlueXP  et leurs autorisations"]
* https://docs.netapp.com/us-en/bluexp-automation/tenancyv4/overview.html["En savoir plus sur l'API pour BlueXP  IAM"^]

