---
sidebar: sidebar 
permalink: reference-iam-storage-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, identity and access management, access roles, admin 
summary: La gestion des identités et des accès BlueXP  fournit deux rôles administratifs que vous pouvez attribuer aux membres de votre organisation. 
---
= Rôles d'accès au stockage pour BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez attribuer les rôles suivants aux utilisateurs pour leur permettre d'accéder aux fonctionnalités de gestion du stockage dans BlueXP  associées aux ressources de stockage prises en charge. Vous pouvez attribuer aux utilisateurs un rôle administratif pour gérer le stockage ou un rôle de spectateur pour la surveillance.


NOTE: Ces rôles ne sont pas disponibles à partir de l’API de partenariat BlueXP.

Les administrateurs peuvent attribuer des rôles de stockage aux utilisateurs pour les ressources et fonctionnalités de stockage suivantes :

Ressources de stockage :

* Clusters ONTAP sur site
* StorageGRID
* E-Series


Services et fonctionnalités BlueXP  :

* Conseiller digital
* Mises à jour de logiciels
* Résilience opérationnelle
* Efficacité économique
* Durabilité


.Exemple pour les rôles de stockage dans BlueXP 
XYZ Corporation, une multinationale, dispose d'une grande équipe d'ingénieurs du stockage et d'administrateurs de stockage. Ils permettent à cette équipe de gérer les actifs de stockage pour leurs régions tout en limitant l'accès aux tâches principales de BlueXP telles que la gestion des utilisateurs, la création de connecteurs et les outils de coûts tels que le portefeuille numérique.

Au sein d'une équipe de 12, deux utilisateurs reçoivent le rôle *Storage Viewer* qui leur permet de surveiller les ressources de stockage associées aux projets BlueXP  auxquels ils sont affectés. Les neuf autres rôles sont attribués à l'administrateur du stockage*, qui comprend la possibilité de gérer les mises à jour logicielles, d'accéder au Gestionnaire système ONTAP via BlueXP  et de découvrir les ressources de stockage (ajout d'environnements de travail). Une personne de l'équipe reçoit le rôle *System Health Specialist* pour gérer l'état des ressources de stockage dans sa région, mais sans modifier ni supprimer d'environnement de travail. Cette personne peut également effectuer des mises à jour logicielles sur les ressources de stockage pour les projets qui lui sont attribués.

L'organisation dispose de deux utilisateurs supplémentaires avec le rôle *Organization admin* qui peuvent gérer tous les aspects de BlueXP , y compris la gestion des utilisateurs, la création de connecteurs et les outils de gestion des coûts tels que le portefeuille numérique, ainsi que plusieurs utilisateurs avec le rôle *Folder ou Project admin* qui peuvent effectuer des tâches d'administration BlueXP  pour les dossiers et les projets auxquels ils sont affectés.

Le tableau suivant présente les actions effectuées par chaque rôle de stockage BlueXP.

[cols="40,20a,20a,20a"]
|===
| Fonction et action | Administrateur du stockage | Spécialiste de l'état du système | Outil de visualisation du stockage 


4+| *Canvas* : 


| Découvrir de nouvelles ressources (créer un nouvel environnement de travail)  a| 
Oui.
 a| 
Oui.
 a| 
Non



| Afficher les ressources découvertes  a| 
Oui.
 a| 
Oui.
 a| 
Non



| Supprimer les environnements de travail  a| 
Oui.
 a| 
Non
 a| 
Non



| Modifier les environnements de travail  a| 
Oui.
 a| 
Non
 a| 
Non



| *Créer un connecteur*  a| 
Non
 a| 
Non
 a| 
Non



4+| *Conseiller numérique* 


| Afficher toutes les pages et fonctions  a| 
Oui.
 a| 
Oui.
 a| 
Oui.



4+| *Porte-monnaie numérique* 


| Afficher toutes les pages et fonctions  a| 
Non
 a| 
Non
 a| 
Non



4+| *Mises à jour logicielles* 


| Consultez la page d'accueil et les recommandations  a| 
Oui.
 a| 
Oui.
 a| 
Oui.



| Passez en revue les recommandations de version et les principaux avantages  a| 
Oui.
 a| 
Oui.
 a| 
Oui.



| Afficher les détails des mises à jour pour un cluster  a| 
Oui.
 a| 
Oui.
 a| 
Oui.



| Exécuter des vérifications avant mise à jour et télécharger le plan de mise à niveau  a| 
Oui.
 a| 
Oui.
 a| 
Oui.



| Installez les mises à jour logicielles  a| 
Oui.
 a| 
Oui.
 a| 
Non



4+| *Résilience opérationnelle* 


| Examinez les problèmes de risque de sécurité  a| 
Oui.
 a| 
Oui.
 a| 
Oui.



| Téléchargez des playbooks Ansible  a| 
Oui.
 a| 
Oui.
 a| 
Non



| Corrigez automatiquement les problèmes  a| 
Oui.
 a| 
Oui.
 a| 
Non



4+| *Efficacité économique* 


| Vérifiez l'état de planification de la capacité  a| 
Oui.
 a| 
Oui.
 a| 
Oui.



| Choisir l'action suivante (meilleure pratique, niveau)  a| 
Oui.
 a| 
Non
 a| 
Non



| Basculez les données inactives vers le stockage cloud et libérez du stockage  a| 
Oui.
 a| 
Oui.
 a| 
Non



| Configurez les rappels  a| 
Oui.
 a| 
Oui.
 a| 
Oui.



4+| *Durabilité* 


| Tableau de bord et recommandations  a| 
Oui.
 a| 
Oui.
 a| 
Oui.



| Télécharger les données du rapport  a| 
Oui.
 a| 
Oui.
 a| 
Oui.



| Modifier le pourcentage d'atténuation du carbone  a| 
Oui.
 a| 
Oui.
 a| 
Non



| Recommandations de réparation  a| 
Oui.
 a| 
Oui.
 a| 
Non



| Reporter les recommandations  a| 
Oui.
 a| 
Oui.
 a| 
Non



4+| *Accès au gestionnaire de système* 


| Peut entrer des informations d'identification  a| 
Oui.
 a| 
Oui.
 a| 
Non



4+| *Informations d'identification* 


| Informations d'identification de l'utilisateur  a| 
Oui.
 a| 
Oui.
 a| 
Non

|===