---
sidebar: sidebar 
permalink: reference-connector-operating-system-changes.html 
keywords: connector, operating systems, connector operating systems, os support, supported operating systems, rhel 8, rhel 9, red hat, docker, podman 
summary: 'Au fur et à mesure que nous ajoutons et supprimons la prise en charge du connecteur sur des systèmes d"exploitation Linux spécifiques, vous pourriez avoir des questions sur la façon dont cette prise en charge affecte vos déploiements de connecteurs existants.' 
---
= Modifications apportées aux systèmes d'exploitation Linux pris en charge
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Au fur et à mesure que nous ajoutons et supprimons la prise en charge du connecteur sur des systèmes d'exploitation Linux spécifiques, vous pourriez avoir des questions sur la façon dont cette prise en charge affecte vos déploiements de connecteurs existants.



== Systèmes d'exploitation pris en charge

NetApp prend en charge le connecteur BlueXP avec les systèmes d’exploitation Linux suivants.

[role="tabbed-block"]
====
.Mode standard
--
Installation manuelle::
+
--
* Ubuntu 24.04 LTS
* Ubuntu 22.04 LTS
* Red Hat Enterprise Linux
+
** 8.6 à 8.10
** 9.1 à 9.4




--
Déploiement à partir de BlueXP:: Ubuntu 22.04 LTS
Déploiement à partir d'AWS Marketplace:: Ubuntu 22.04 LTS
Déploiement à partir d'Azure Marketplace:: Ubuntu 22.04 LTS


--
.Mode restreint
--
Installation manuelle::
+
--
* Ubuntu 24.04 LTS
* Ubuntu 22.04 LTS
* Red Hat Enterprise Linux
+
** 8.6 à 8.10
** 9.1 à 9.4




--
Déploiement à partir d'AWS Marketplace:: Ubuntu 22.04 LTS
Déploiement à partir d'Azure Marketplace:: Ubuntu 22.04 LTS


--
.Mode privé
--
Installation manuelle::
+
--
* Ubuntu 22.04 LTS
* Red Hat Enterprise Linux
+
** 8.6 à 8.10
** 9.1 à 9.4




--


--
====


== Prise en charge de RHEL 8 et 9

Notez les points suivants concernant la prise en charge de RHEL 8 et 9 :

Limites:: La classification BlueXP est prise en charge si vous installez le connecteur sur un hôte RHEL 8 ou 9 résidant sur site. Elle n'est pas prise en charge si l'hôte RHEL 8 ou 9 réside dans AWS, Azure ou Google Cloud.
Outil d'orchestration de conteneurs:: Vous devez utiliser l’outil Podman comme outil d’orchestration de conteneur lors de l’installation du connecteur sur un hôte RHEL 8 ou 9. Docker Engine n'est pas pris en charge par RHEL 8 et 9.
Mode de déploiement:: RHEL 8 et 9 sont pris en charge lorsque BlueXP est utilisé en mode standard, en mode restreint et en mode privé.
Versions de connecteur prises en charge:: NetApp prend en charge RHEL 8 et 9 à partir des versions suivantes du connecteur :
+
--
* 3.9.40 lors de l'utilisation de BlueXP  en mode standard ou en mode restreint
* 3.9.42 lors de l'utilisation de BlueXP  en mode privé


--
Nouvelles installations manuelles uniquement:: RHEL 8 et 9 sont pris en charge avec les installations _New_ Connector lors de l'installation manuelle du connecteur sur des hôtes exécutés sur votre site ou dans le cloud.
Mises à niveau de RHEL:: Si vous disposez d'un connecteur existant sur un hôte RHEL 7, nous ne prenons pas en charge la mise à niveau du système d'exploitation RHEL 7 vers RHEL 8 ou 9. <<Connecteurs existants sur RHEL 7 ou CentOS 7,En savoir plus sur les connecteurs existants sur RHEL 7 ou CentOS 7>>.




== Fin de la prise en charge de RHEL 7 et CentOS 7

Le 30 juin 2024, RHEL 7 a atteint la fin de maintenance (EOM), tandis que CentOS 7 a atteint la fin de vie (EOL). NetApp a cessé de prendre en charge le connecteur sur ces distributions Linux le 30 juin 2024.

https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux/rhel-7-end-of-maintenance["Red Hat : que savoir sur la fin de la maintenance de Red Hat Enterprise Linux 7"^]



=== Connecteurs existants sur RHEL 7 ou CentOS 7

Si vous disposez d'un connecteur existant fonctionnant sur RHEL 7 ou CentOS 7, nous ne prenons pas en charge la mise à niveau ou la conversion du système d'exploitation vers RHEL 8 ou 9. Vous devez créer un nouveau connecteur sur un système d’exploitation pris en charge.

. Configurez un hôte RHEL 8 ou 9.
. Installez Podman.
. Installer un connecteur _neuf_.
. Configurez le connecteur pour découvrir les environnements de travail gérés par l'ancien connecteur.




== Informations associées



=== Comment démarrer avec RHEL 8 et 9

Reportez-vous aux pages suivantes pour plus de détails sur la configuration requise pour l'hôte, la configuration requise pour Podman et les étapes d'installation de Podman et du connecteur :

[role="tabbed-block"]
====
.Mode standard
--
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["Installer et configurer un connecteur sur site"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-manual.html["Installez manuellement le connecteur dans AWS"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-azure-manual.html["Installez manuellement le connecteur dans Azure"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-google-manual.html["Installez manuellement le connecteur dans Google Cloud"]


--
.Mode restreint
--
https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-restricted-mode.html["Préparez le déploiement en mode restreint"]

--
.Mode privé
--
https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html["Préparez le déploiement en mode privé"]

--
====


=== Comment redécouvrir vos environnements de travail

Reportez-vous aux pages suivantes pour redécouvrir vos environnements de travail après le déploiement d'un nouveau connecteur.

* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-adding-systems.html["Ajout de systèmes Cloud Volumes ONTAP existants à BlueXP"^]
* https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["Découvrez les clusters ONTAP sur site"^]
* https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-creating-fsx-working-environment.html["Créez ou découvrez un environnement de travail FSX pour ONTAP"^]
* https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-create-working-env.html["Créer un environnement de travail Azure NetApp Files"^]
* https://docs.netapp.com/us-en/bluexp-e-series/task-discover-e-series.html["Découvrez les systèmes E-Series"^]
* https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["Découvrir les systèmes StorageGRID"^]

