---
sidebar: sidebar 
permalink: reference-permissions.html 
keywords: permissions, actions 
summary: Pour utiliser les fonctionnalités et services de BlueXP, vous devez fournir des autorisations pour que BlueXP puisse effectuer des opérations dans votre environnement cloud. Utilisez les liens de cette page pour accéder rapidement aux autorisations requises dans BlueXP. 
---
= Résumé des autorisations pour BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Pour utiliser les fonctionnalités et services de BlueXP, vous devez fournir des autorisations pour que BlueXP puisse effectuer des opérations dans votre environnement cloud. Utilisez les liens de cette page pour accéder rapidement aux autorisations dont vous avez besoin en fonction de votre objectif.



== Autorisations AWS

[cols="25,60,40"]
|===
| Objectif | Description | Lien 


| Déployez des connecteurs à partir de BlueXP | L'utilisateur qui crée un connecteur depuis BlueXP a besoin d'autorisations spécifiques pour déployer l'instance dans AWS. | link:task-set-up-permissions-aws.html["Configurez les autorisations AWS"] 


| Fonctionnement du connecteur | Lorsque BlueXP lance le connecteur, il attache une stratégie à l'instance qui fournit les autorisations nécessaires pour gérer les ressources et les processus de votre compte AWS.

Vous devez configurer la stratégie vous-même si vous lancez un connecteur à partir du Marketplace, installez manuellement le connecteur ou si vous le souhaitez link:task-adding-aws-accounts.html#add-additional-credentials-to-a-connector["Ajoutez des identifiants AWS à un connecteur"].

Vous devez également vous assurer que la stratégie est à jour lorsque de nouvelles autorisations sont ajoutées dans les versions suivantes. | link:reference-permissions-aws.html["Autorisations AWS pour le connecteur"] 


| Fonctionnement du Cloud Volumes ONTAP | Un rôle IAM doit être associé à chaque nœud Cloud Volumes ONTAP dans AWS. Il en va de même pour le médiateur HA. L'option par défaut est de permettre à BlueXP de créer les rôles IAM pour vous, mais vous pouvez utiliser votre propre. | https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-set-up-iam-roles.html["Découvrez comment configurer vous-même les rôles IAM"^] 
|===


== Autorisations Azure

[cols="25,60,40"]
|===
| Objectif | Description | Lien 


| Déployez des connecteurs à partir de BlueXP | Lorsque vous déployez un connecteur depuis BlueXP, vous devez utiliser un compte ou un service principal Azure disposant des autorisations pour déployer la machine virtuelle Connector dans Azure. | link:task-set-up-permissions-azure.html["Configurez les autorisations Azure"] 


| Fonctionnement du connecteur  a| 
Lorsque BlueXP déploie la machine virtuelle Connector dans Azure, il crée un rôle personnalisé qui fournit les autorisations requises pour gérer les ressources et les processus au sein de cet abonnement Azure.

Vous devez configurer vous-même le rôle personnalisé si vous lancez un connecteur à partir du Marketplace, installez manuellement le connecteur ou si vous le souhaitez link:task-adding-azure-accounts.html#adding-additional-azure-credentials-to-cloud-manager["Ajoutez des identifiants Azure à un connecteur"].

Vous devez également vous assurer que la stratégie est à jour lorsque de nouvelles autorisations sont ajoutées dans les versions suivantes.
 a| 
link:reference-permissions-azure.html["Autorisations Azure pour le connecteur"]

|===


== Autorisations Google Cloud

[cols="25,60,40"]
|===
| Objectif | Description | Lien 


| Déploiement de connecteurs | L'utilisateur Google Cloud qui déploie un connecteur depuis BlueXP a besoin d'autorisations spécifiques pour déployer le connecteur dans Google Cloud. | link:task-set-up-permissions-google.html#set-up-permissions-to-create-the-connector-from-bluexp-or-gcloud["Configurez les autorisations de déploiement du connecteur"] 


| Fonctionnement du connecteur | Le compte de service de l'instance de VM Connector doit disposer d'autorisations spécifiques pour les opérations quotidiennes. Vous devez associer le compte de service au connecteur lorsque vous le déployez depuis BlueXP.

Vous devez également vous assurer que la stratégie est à jour lorsque de nouvelles autorisations sont ajoutées dans les versions suivantes. | link:reference-permissions-gcp.html["Autorisations Google Cloud pour le connecteur"] 
|===