---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, active directory, ad, iscsi, key managers, ip address, govcloud, BlueXP, Cloud Volumes ONTAP, days, running, Connectors should remain running, imdsv2, httpstokens 
summary: Les limitations connues identifient les plateformes, les périphériques ou les fonctions qui ne sont pas pris en charge par cette version du produit, ou qui ne fonctionnent pas correctement avec elle. Examinez attentivement ces limites. 
---
= Limites connues
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les limitations connues identifient les plateformes, les périphériques ou les fonctions qui ne sont pas pris en charge par cette version du produit, ou qui ne fonctionnent pas correctement avec elle. Examinez attentivement ces limites.

Ces limitations sont spécifiques à la configuration et à l'administration de BlueXP : le connecteur, la plate-forme SaaS, et plus encore.



== Limitations du connecteur



=== Conflit possible avec les adresses IP dans la plage 172

BlueXP déploie le connecteur avec deux interfaces qui ont des adresses IP dans les plages 172.17.0.0/16 et 172.18.0.0/16.

Si votre réseau dispose d'un sous-réseau configuré avec l'une ou l'autre de ces plages, il se peut que vous ayez des défaillances de connectivité de BlueXP. Par exemple, la découverte de clusters ONTAP sur site dans BlueXP peut échouer.

Consultez l'article de la base de connaissances link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Manager/Cloud_Manager_shows_inactive_as_Connector_IP_range_in_172.x.x.x_conflict_with_docker_network["Conflit IP connecteur BlueXP avec le réseau existant"] Pour obtenir des instructions sur la modification de l’adresse IP des interfaces du connecteur.



=== Le décryptage SSL n'est pas pris en charge

BlueXP ne prend pas en charge les configurations de pare-feu pour lesquelles le décryptage SSL est activé. Si le décryptage SSL est activé, des messages d'erreur apparaissent dans BlueXP et l'instance de connecteur s'affiche comme inactive.

Pour une sécurité améliorée, vous avez la possibilité de link:task-installing-https-cert.html["Installation d'un certificat HTTPS signé par une autorité de certification (CA)"].



=== Page blanche lors du chargement de l'interface utilisateur locale

Si vous chargez la console Web qui s'exécute sur un connecteur, l'interface peut ne pas s'afficher parfois et vous obtenez juste une page vierge.

Ce problème est lié à un problème de mise en cache. La solution consiste à utiliser une session de navigateur Web privée ou incognito.



=== Les hôtes Linux partagés ne sont pas pris en charge

Le connecteur n'est pas pris en charge sur une machine virtuelle partagée avec d'autres applications. La machine virtuelle doit être dédiée au logiciel de connecteur.



=== agents et extensions tiers

Les agents tiers ou les extensions VM ne sont pas pris en charge sur la VM Connector.
