---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking 
summary: 'Lorsque vous utilisez la console web BlueXP fournie via la couche SaaS, il contacte plusieurs terminaux lorsqu"il effectue quelques tâches d"administration. Les ordinateurs qui accèdent à la console BlueXP doivent avoir des connexions à ces terminaux.' 
---
= Préparez la mise en réseau pour la console BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lorsque vous vous connectez et utilisez la console Web, BlueXP contacte plusieurs points de terminaison pour exécuter les actions que vous avez initiées. Les ordinateurs qui accèdent à la console doivent être connectés à ces points de terminaison.

Ces terminaux sont contactés dans deux scénarios :

* Depuis l'ordinateur d'un utilisateur lors de la complétion de sections du https://console.bluexp.netapp.com["Console web BlueXP"^] qui est disponible sous forme de logiciel en tant que service (SaaS).
* À partir de l'ordinateur d'un utilisateur lors de l'ouverture d'un navigateur Web, en entrant l'adresse IP de l'hôte du connecteur, puis en se connectant et en configurant le connecteur. Ces étapes sont nécessaires si vous installez manuellement le connecteur.


[cols="2*"]
|===
| Terminaux | Objectif 


| \https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com | Il s’agit du point de terminaison que vous entrez dans votre navigateur Web pour utiliser la console Web. 


| \https://api.bluexp.netapp.com | La console Web contacte ce point de terminaison pour interagir avec l'API pour les actions liées à l'autorisation, aux licences, aux abonnements, aux informations d'identification, aux notifications, etc. 


| \https://aiq.netapp.com | Obligatoire pour accéder au conseiller numérique. 


 a| 
Services AWS (amazonaws.com):

* CloudFormation
* Cloud de calcul élastique (EC2)
* Service de gestion des clés (KMS)
* Service de jetons de sécurité (STS)
* Service de stockage simple (S3)

| Nécessaire pour déployer un connecteur depuis BlueXP dans AWS. Le point de terminaison exact dépend de la région dans laquelle vous déployez le connecteur.  https://docs.aws.amazon.com/general/latest/gr/rande.html["Consultez la documentation AWS pour plus de détails."] Suggestion:  https://docs.aws.amazon.com/general/latest/gr/rande.html["Consultez la documentation AWS pour plus de détails."] 


| \https://management.azure.com

\https://login.microsoftonline.com | Nécessaire au déploiement d'un connecteur depuis BlueXP dans la plupart des régions Azure. 


| \https://management.microsoftazure.de

\https://login.microsoftonline.de | Nécessaire au déploiement d'un connecteur depuis BlueXP dans les régions d'Azure Allemagne. 


| \https://management.usgovcloudapi.net

\https://login.microsoftonline.com | Nécessaire au déploiement d'un connecteur de BlueXP dans les régions Azure Government. 


| \https://www.googleapis.com | Nécessaire pour déployer un connecteur depuis BlueXP dans Google Cloud. 


| \https://signin.b2c.netapp.com | Requis pour mettre à jour les identifiants du site de support NetApp (NSS) ou pour ajouter de nouvelles informations d'identification NSS à BlueXP. 


| \ https://netapp-cloud-account.auth0.com \ https://netapp-cloud-account.us.auth0.com \ https://cdn.auth0.com \ https://services.cloud.netapp.com | Votre navigateur Web se connecte à ces points de terminaison pour une authentification utilisateur centralisée via BlueXP. 


| \https://widget.intercom.io | Pour le chat intégré au produit qui vous permet de parler au support NetApp. 
|===
Assurez-vous que le connecteur dispose d'un accès Internet sortant pour contacter les points de terminaison pour les opérations quotidiennes. Suivez les liens de la section suivante pour trouver la liste de ces points de terminaison.

.Informations associées
* Préparez la mise en réseau pour le connecteur
+
** link:task-install-connector-aws-bluexp.html#step-1-set-up-networking["Configuration du réseau AWS"]
** link:task-install-connector-azure-bluexp.html#step-1-set-up-networking["Configuration du réseau Azure"]
** link:task-install-connector-google-bluexp-gcloud.html#step-1-set-up-networking["Configuration du réseau Google Cloud"]
** link:task-install-connector-on-prem.html#step-3-set-up-networking["Configurer un réseau sur site"]


* Préparez la mise en réseau pour les services BlueXP
+
Consultez la documentation de chaque service BlueXP.

+
https://docs.netapp.com/us-en/bluexp-family/["Documentation BlueXP"^]


