---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking 
summary: 'Lorsque vous utilisez la console web BlueXP fournie via la couche SaaS, il contacte plusieurs terminaux lorsqu"il effectue quelques tâches d"administration. Les ordinateurs qui accèdent à la console BlueXP doivent avoir des connexions à ces terminaux.' 
---
= Préparez la mise en réseau pour la console BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lorsque vous vous connectez et utilisez la console Web BlueXP , BlueXP  contacte plusieurs points finaux pour effectuer les actions que vous lancez. Les ordinateurs qui accèdent à la console BlueXP  doivent avoir des connexions à ces noeuds finaux.

Ces terminaux sont contactés dans deux scénarios :

* À partir de l'ordinateur d'un utilisateur lors de l'exécution d'actions spécifiques à partir du https://console.bluexp.netapp.com["Console web BlueXP"^] qui est disponible en tant que logiciel en tant que service (SaaS).
* À partir de l'ordinateur d'un utilisateur lors de l'ouverture d'un navigateur Web, en entrant l'adresse IP de l'hôte du connecteur, puis en se connectant et en configurant le connecteur. Ces étapes sont nécessaires si vous installez manuellement le connecteur.


[cols="2*"]
|===
| Terminaux | Objectif 


| \https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com | Il s'agit du noeud final que vous entrez dans votre navigateur Web pour utiliser la console Web BlueXP . 


| \https://api.bluexp.netapp.com | La console Web BlueXP  contacte ce terminal pour interagir avec l'API BlueXP  afin d'effectuer des actions liées aux autorisations, aux licences, aux abonnements, aux informations d'identification, aux notifications, etc. 


| \https://aiq.netapp.com | Requis pour accéder au conseiller digital BlueXP. 


 a| 
Services AWS (amazonaws.com):

* CloudFormation
* Cloud de calcul élastique (EC2)
* Service de gestion des clés (KMS)
* Service de jetons de sécurité (STS)
* Service de stockage simple (S3)

| Nécessaire pour déployer un connecteur depuis BlueXP dans AWS. Le point final exact dépend de la région dans laquelle vous déployez le connecteur. https://docs.aws.amazon.com/general/latest/gr/rande.html["Reportez-vous à la documentation AWS pour plus de détails."^] 


| \https://management.azure.com

\https://login.microsoftonline.com | Nécessaire au déploiement d'un connecteur depuis BlueXP dans la plupart des régions Azure. 


| \https://management.microsoftazure.de

\https://login.microsoftonline.de | Nécessaire au déploiement d'un connecteur depuis BlueXP dans les régions d'Azure Allemagne. 


| \https://management.usgovcloudapi.net

\https://login.microsoftonline.com | Nécessaire au déploiement d'un connecteur de BlueXP dans les régions Azure Government. 


| \https://www.googleapis.com | Nécessaire pour déployer un connecteur depuis BlueXP dans Google Cloud. 


| \https://signin.b2c.netapp.com | Requis pour mettre à jour les identifiants du site de support NetApp (NSS) ou pour ajouter de nouvelles informations d'identification NSS à BlueXP. 


| \https://netapp-cloud-account.auth0.com

\https://cdn.auth0.com

\https://services.cloud.netapp.com | Votre navigateur Web se connecte à ces points de terminaison pour une authentification utilisateur centralisée via BlueXP. 


| \https://widget.intercom.io | Vous bénéficiez d'un chat en ligne pour discuter avec des experts du cloud NetApp. 
|===
Au-delà de ces terminaux, vous devez également vous assurer que le connecteur dispose d'un accès Internet sortant pour contacter des terminaux spécifiques pour les opérations quotidiennes. Vous trouverez la liste de ces points d'extrémité en suivant les liens de la section suivante ci-dessous.

.Informations associées
* Préparez la mise en réseau pour le connecteur
+
** link:task-install-connector-aws-bluexp.html#step-1-set-up-networking["Configuration du réseau AWS"]
** link:task-install-connector-azure-bluexp.html#step-1-set-up-networking["Configuration du réseau Azure"]
** link:task-install-connector-google-bluexp-gcloud.html#step-1-set-up-networking["Configuration du réseau Google Cloud"]
** link:task-install-connector-on-prem.html#step-3-set-up-networking["Configurer un réseau sur site"]


* Préparez la mise en réseau pour les services BlueXP
+
Consultez la documentation de chaque service BlueXP.

+
https://docs.netapp.com/us-en/bluexp-family/["Documentation BlueXP"^]


