---
sidebar: sidebar 
permalink: task-set-up-permissions-aws.html 
keywords: aws permissions, set up permissions, set up aws permissions, permissions, iam role, iam policy, json, policy, role, credentials 
summary: 'Configurez les autorisations dans AWS pour que vous puissiez déployer le connecteur avec les autorisations dont les équipes IT ont besoin pour gérer vos données et votre infrastructure de stockage. La manière dont vous configurez et fournissez les autorisations dépend de l"option d"installation que vous prévoyez d"utiliser.' 
---
= Configurez les autorisations AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Configurez les autorisations dans AWS pour que vous puissiez déployer le connecteur avec les autorisations dont les équipes IT ont besoin pour gérer vos données et votre infrastructure de stockage. La manière dont vous configurez et fournissez les autorisations dépend de l'option d'installation que vous prévoyez d'utiliser.

Vous pouvez choisir parmi les options d'installation suivantes :

* *Installer à partir de BlueXP* : configurez des autorisations qui permettent à BlueXP de s'authentifier auprès d'AWS et de déployer l'instance. BlueXP configure automatiquement les autorisations pour l'instance Connector pendant le déploiement.
+
<<Configurez les autorisations pour créer le connecteur à partir de BlueXP,Affichez les instructions détaillées>>.

* *Installer à partir d'AWS Marketplace* : configurez un rôle IAM que vous pouvez associer à l'instance de connecteur.
+
<<Configurez les autorisations pour le connecteur lors d'un déploiement à partir d'AWS Marketplace,Affichez les instructions détaillées>>.

* *Manual install* : créez des stratégies IAM et attachez-les à un rôle IAM ou à un utilisateur IAM.
+
<<Définissez les autorisations à attribuer après l'installation manuelle,Affichez les instructions détaillées>>.





== Configurez les autorisations pour créer le connecteur à partir de BlueXP

BlueXP doit s'authentifier auprès d'AWS avant de pouvoir déployer l'instance de connecteur dans votre VPC. Vous pouvez choisir l'une des méthodes d'authentification suivantes :

* BlueXP assume un rôle IAM qui dispose des autorisations requises
* Fournissez une clé d'accès AWS et une clé secrète pour un utilisateur IAM qui dispose des autorisations nécessaires


Quelle que soit l'option choisie, la première étape consiste à créer une politique IAM. Cette politique contient uniquement les autorisations nécessaires pour lancer l'instance Connector dans AWS à partir de BlueXP.

Si nécessaire, vous pouvez restreindre la politique IAM à l'aide de l'IAM `Condition` elément. https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition.html["Documentation AWS : élément de condition"^]


TIP: Lorsque BlueXP crée le connecteur, il applique un nouvel ensemble d'autorisations à l'instance Connector qui permet au connecteur de gérer les ressources AWS.

.Étapes
. Accédez à la console IAM AWS.
. Sélectionnez *stratégies > Créer une stratégie*.
. Sélectionnez *JSON*.
. Copiez et collez la stratégie suivante :
+
Pour rappel, cette règle contient uniquement les autorisations nécessaires pour lancer l'instance Connector dans AWS à partir de BlueXP. link:reference-permissions-aws.html["Droits d'accès requis pour l'instance de connecteur elle-même"].

+
[source, json]
----
{
    "Version": "2012-10-17",
    "Statement": [{
            "Effect": "Allow",
            "Action": [
                "iam:CreateRole",
                "iam:DeleteRole",
                "iam:PutRolePolicy",
                "iam:CreateInstanceProfile",
                "iam:DeleteRolePolicy",
                "iam:AddRoleToInstanceProfile",
                "iam:RemoveRoleFromInstanceProfile",
                "iam:DeleteInstanceProfile",
                "iam:PassRole",
                "ec2:DescribeInstanceStatus",
                "ec2:RunInstances",
                "ec2:ModifyInstanceAttribute",
                "ec2:CreateSecurityGroup",
                "ec2:DeleteSecurityGroup",
                "ec2:DescribeSecurityGroups",
                "ec2:RevokeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:RevokeSecurityGroupIngress",
                "ec2:CreateNetworkInterface",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DeleteNetworkInterface",
                "ec2:ModifyNetworkInterfaceAttribute",
                "ec2:DescribeSubnets",
                "ec2:DescribeVpcs",
                "ec2:DescribeDhcpOptions",
                "ec2:DescribeKeyPairs",
                "ec2:DescribeRegions",
                "ec2:DescribeInstances",
                "ec2:CreateTags",
                "ec2:DescribeImages",
                "cloudformation:CreateStack",
                "cloudformation:DeleteStack",
                "cloudformation:DescribeStacks",
                "cloudformation:DescribeStackEvents",
                "cloudformation:ValidateTemplate",
                "ec2:AssociateIamInstanceProfile",
                "ec2:DescribeIamInstanceProfileAssociations",
                "ec2:DisassociateIamInstanceProfile",
                "iam:GetRole",
                "iam:TagRole",
                "iam:ListRoles",
                "kms:ListAliases"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:TerminateInstances"
            ],
            "Condition": {
                "StringLike": {
                    "ec2:ResourceTag/OCCMInstance": "*"
                }
            },
            "Resource": [
                "arn:aws:ec2:*:*:instance/*"
            ]
        }
    ]
}
----
. Sélectionnez *Suivant* et ajoutez des balises, si nécessaire.
. Sélectionnez *Suivant* et entrez un nom et une description.
. Sélectionnez *Créer une stratégie*.
. Reliez la règle à un rôle IAM que BlueXP peut assumer ou à un utilisateur IAM pour que vous puissiez fournir BlueXP avec des clés d'accès :
+
** (Option 1) configurer un rôle IAM que BlueXP peut assumer :
+
... Accédez à la console IAM AWS dans le compte cible.
... Sous gestion des accès, sélectionnez *rôles > Créer un rôle* et suivez les étapes pour créer le rôle.
... Sous *Type d'entité approuvée*, sélectionnez *compte AWS*.
... Sélectionnez *un autre compte AWS* et saisissez l'ID du compte BlueXP SaaS : 952013314444
... Sélectionnez la stratégie que vous avez créée dans la section précédente.
... Après avoir créé le rôle, copiez le rôle ARN afin de pouvoir le coller dans BlueXP lorsque vous créez le connecteur.


** (Option 2) configurez les autorisations d'accès pour un utilisateur IAM afin que vous puissiez fournir BlueXP avec des clés d'accès :
+
... Dans la console IAM AWS, sélectionnez *Users*, puis sélectionnez le nom d'utilisateur.
... Sélectionnez *Ajouter des autorisations > joindre des stratégies existantes directement*.
... Sélectionnez la stratégie que vous avez créée.
... Sélectionnez *Suivant*, puis *Ajouter des autorisations*.
... Assurez-vous que vous disposez de la clé d'accès et de la clé secrète pour l'utilisateur IAM.






.Résultat
Vous devez maintenant disposer d'un rôle IAM qui possède les autorisations requises ou d'un utilisateur IAM qui dispose des autorisations requises. Lorsque vous créez le connecteur à partir de BlueXP, vous pouvez fournir des informations sur le rôle ou les clés d'accès.



== Configurez les autorisations pour le connecteur lors d'un déploiement à partir d'AWS Marketplace

Pour préparer un déploiement Marketplace, créez des politiques IAM dans AWS et associez-les à un rôle IAM. Lorsque vous créez le connecteur à partir d'AWS Marketplace, vous êtes invité à sélectionner ce rôle IAM.

.Étapes
. Connectez-vous à la console AWS et accédez au service IAM.
. Création d'une règle :
+
.. Sélectionnez *stratégies > Créer une stratégie*.
.. Sélectionnez *JSON* et copiez et collez le contenu du link:reference-permissions-aws.html["Politique IAM pour le connecteur"].
.. Terminez les étapes restantes pour créer la stratégie.
+
Selon les services BlueXP que vous prévoyez d'utiliser, il peut être nécessaire de créer une seconde règle. Pour les régions standard, les autorisations sont réparties entre deux règles. Deux règles sont requises en raison d'une taille maximale de caractères pour les stratégies gérées dans AWS. link:reference-permissions-aws.html["En savoir plus sur les règles IAM pour le connecteur"].



. Créer un rôle IAM :
+
.. Sélectionnez *rôles > Créer un rôle*.
.. Sélectionnez *AWS service > EC2*.
.. Ajoutez des autorisations en joignant la stratégie que vous venez de créer.
.. Terminez les étapes restantes pour créer le rôle.




.Résultat
Vous pouvez désormais associer un rôle IAM à l'instance EC2 lors du déploiement depuis AWS Marketplace.



== Définissez les autorisations à attribuer après l'installation manuelle

Si vous prévoyez d'installer manuellement le logiciel Connector sur votre propre hôte Linux dans AWS, vous pouvez fournir les autorisations de plusieurs manières :

* Option 1 : créez des règles IAM et associez-les à un rôle IAM que vous pouvez associer à l'instance EC2.
* Option 2 : fournissez à BlueXP des clés d'accès AWS pour un utilisateur IAM qui dispose des autorisations requises.


[role="tabbed-block"]
====
.Rôle IAM
--
.Étapes
. Connectez-vous à la console AWS et accédez au service IAM.
. Création d'une règle :
+
.. Sélectionnez *stratégies > Créer une stratégie*.
.. Sélectionnez *JSON* et copiez et collez le contenu du link:reference-permissions-aws.html["Politique IAM pour le connecteur"].
.. Terminez les étapes restantes pour créer la stratégie.
+
Selon les services BlueXP que vous prévoyez d'utiliser, il peut être nécessaire de créer une seconde règle. Pour les régions standard, les autorisations sont réparties entre deux règles. Deux règles sont requises en raison d'une taille maximale de caractères pour les stratégies gérées dans AWS. link:reference-permissions-aws.html["En savoir plus sur les règles IAM pour le connecteur"].



. Créer un rôle IAM :
+
.. Sélectionnez *rôles > Créer un rôle*.
.. Sélectionnez *AWS service > EC2*.
.. Ajoutez des autorisations en joignant la stratégie que vous venez de créer.
.. Terminez les étapes restantes pour créer le rôle.




.Résultat
Vous disposez désormais d'un rôle IAM que vous pouvez associer à l'instance EC2 après avoir installé le connecteur. link:task-provide-permissions-aws.html["Découvrez comment fournir ces autorisations à BlueXP"].

--
.Clé d'accès AWS
--
.Étapes
. Connectez-vous à la console AWS et accédez au service IAM.
. Création d'une règle :
+
.. Sélectionnez *stratégies > Créer une stratégie*.
.. Sélectionnez *JSON* et copiez et collez le contenu du link:reference-permissions-aws.html["Politique IAM pour le connecteur"].
.. Terminez les étapes restantes pour créer la stratégie.
+
Selon les services BlueXP que vous prévoyez d'utiliser, il peut être nécessaire de créer une seconde règle.

+
Pour les régions standard, les autorisations sont réparties entre deux règles. Deux règles sont requises en raison d'une taille maximale de caractères pour les stratégies gérées dans AWS. link:reference-permissions-aws.html["En savoir plus sur les règles IAM pour le connecteur"].



. Associer les règles à un utilisateur IAM.
+
** https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create.html["Documentation AWS : création de rôles IAM"^]
** https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_manage-attach-detach.html["Documentation AWS : ajout et suppression de règles IAM"^]


. Assurez-vous que l'utilisateur dispose d'une clé d'accès que vous pouvez ajouter à BlueXP après l'installation du connecteur.


.Résultat
Vous disposez désormais d'un utilisateur IAM qui dispose des autorisations requises et d'une clé d'accès que vous pouvez fournir à BlueXP. link:task-provide-permissions-aws.html["Découvrez comment fournir ces autorisations à BlueXP"].

--
====