---
sidebar: sidebar 
permalink: task-log-in-private-mode.html 
keywords: logging in, log in, sign in, signing in, private mode, private mode log in, local log in, connector log in, log in connector 
summary: 'Lorsque vous utilisez BlueXP en mode privé, vous devez vous connecter à la console BlueXP à partir de l"interface utilisateur qui s"exécute localement sur le connecteur.' 
---
= Se connecter à BlueXP (mode privé)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lorsque vous utilisez BlueXP en mode privé, vous devez vous connecter à la console BlueXP à partir de l'interface utilisateur qui s'exécute localement sur le connecteur.

.Options de connexion
Le mode privé prend en charge la gestion et l'accès des utilisateurs locaux. L'authentification n'est pas fournie via le service cloud de BlueXP.

.Étapes
. Ouvrez un navigateur Web et entrez l'URL suivante :
+
https://_ipaddress_[]

+
_Ipaddress_ peut être localhost, une adresse IP privée ou une adresse IP publique, selon la configuration de l'hôte où vous avez installé le connecteur. Par exemple, vous devrez peut-être entrer une adresse IP privée à partir d'un hôte qui a une connexion à l'hôte du connecteur.

. Entrez votre nom d'utilisateur et votre mot de passe pour vous connecter.


.Résultat
Vous êtes maintenant connecté et pouvez commencer à utiliser BlueXP pour gérer votre infrastructure multicloud hybride.
