---
sidebar: sidebar 
permalink: task-maintain-connectors.html 
keywords: connector operating system, connector maintenance, vm maintenance, os updates, operating system updates, stop connector, restart connector, notifications, connector health, connector disk space, connector cpu usage, connector ram usage, connector vm, connector ip address, connector uri 
summary: 'La maintenance du système d"exploitation sur l"hôte du connecteur relève de votre responsabilité. Par exemple, vous devez appliquer des mises à jour de sécurité au système d"exploitation sur l"hôte du connecteur en suivant les procédures standard de votre entreprise pour la distribution du système d"exploitation.' 
---
= Maintenance de la VM connecteur et du système d'exploitation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La maintenance du système d'exploitation sur l'hôte Connector est de votre responsabilité (en tant que client). Par exemple, vous devez appliquer les mises à jour de sécurité du système d'exploitation sur l'hôte Connector en suivant les procédures standard de votre entreprise pour la distribution des systèmes d'exploitation.


TIP: Si vous disposez d'un connecteur existant, vous devez en être conscient link:reference-connector-operating-system-changes.html["Modifications apportées aux systèmes d'exploitation Linux pris en charge"].



== Correctifs du système d'exploitation et le connecteur

Appliquez les correctifs de sécurité du système d’exploitation sans arrêter les services hôtes du connecteur.



== Type de machine virtuelle ou d'instance

Si vous créez un connecteur depuis BlueXP, une instance de VM est déployée chez votre fournisseur cloud avec une configuration par défaut. Après avoir créé le connecteur, ne passez pas à une instance de VM plus petite, avec moins de CPU ou de RAM.

Le tableau suivant répertorie les exigences en matière de CPU et de RAM :

CPU:: 8 cœurs ou 8 CPU virtuels
RAM:: 32 GO


link:reference-connector-default-config.html["En savoir plus sur la configuration par défaut du connecteur"].



== Surveiller le connecteur

BlueXP vous avertit lorsque la VM du connecteur présente des problèmes d'espace disque, de RAM et de processeur. Surveillez ces notifications dans le Centre de notifications de BlueXP ou configurez des notifications par e-mail. Des augmentations occasionnelles de l'espace disque, de la mémoire ou de l'utilisation du processeur sont normales, mais si elles se produisent fréquemment, vous devez prendre des mesures pour y remédier.

BlueXP vous avertit lorsqu'une ressource du connecteur (processeur, RAM ou espace disque) dépasse 90 % de sa capacité totale pendant 30 minutes consécutives. Par la suite, si l'utilisation de la ressource redescend sous ce seuil, la notification s'affiche comme résolue (en vert) dans le Centre de notifications.


NOTE: Travaillez avec le support NetApp si vous avez des questions sur la modification de votre VM Connector.

link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#notification-center["En savoir plus ."^]

[cols="47,47"]
|===
| Notification | Action nécessaire 


| L'espace disque est trop élevé | link:https://kb.netapp.com/Cloud/BlueXP/Cloud_Manager/How_to_resolve_disk_space_issues_on_BlueXP_connector_VM["Consultez l'article de la base de connaissances NetApp"^]. 


| L'utilisation du processeur est trop élevée | Augmentez la taille du processeur de la VM Connector dans votre hyperscaler ou sur site, selon l'emplacement d'installation. Vous pouvez également créer des connecteurs supplémentaires et répartir la charge de travail sur plusieurs connecteurs. L'utilisation de la RAM peut varier en fonction de votre environnement, des charges de travail ONTAP , du nombre de systèmes Cloud Volumes ONTAP et des services de données utilisés. 


| L'utilisation de la RAM est trop élevée | Augmentez la RAM de la VM Connector dans votre hyperscaler ou sur site, selon l'emplacement d'installation. Vous pouvez également créer des connecteurs supplémentaires et répartir la charge de travail sur plusieurs connecteurs. L'utilisation de la RAM peut varier en fonction de votre environnement, des charges de travail ONTAP , du nombre de systèmes Cloud Volumes ONTAP et des services de données utilisés. 
|===


== Arrêt et démarrage de la VM connecteur

Si nécessaire, arrêtez et démarrez la machine virtuelle Connector à l'aide de la console de votre fournisseur de cloud ou des procédures standard sur site.

link:concept-connectors.html#connectors-must-be-operational-at-all-times["Notez que le connecteur doit être opérationnel en permanence"].



== Connectez-vous à la machine virtuelle Linux

Si vous devez vous connecter à la machine virtuelle Linux sur laquelle le connecteur s’exécute, utilisez les options de connectivité de votre fournisseur de cloud.

AWS:: Lors de la création de l'instance Connector dans AWS, fournissez une clé d'accès AWS et une clé secrète. Vous pouvez utiliser cette paire de clés vers SSH à l'instance. Utilisez le nom d'utilisateur « ubuntu » pour l'instance EC2 Linux. Pour les connecteurs créés avant mai 2023, utilisez le nom d'utilisateur « ec2-user ».
+
--
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstances.html["AWS Docs : connectez-vous à votre instance Linux"^]

--
Azure:: Lorsque vous créez la machine virtuelle Connector dans Azure, vous spécifiez un nom d’utilisateur et choisissez de vous authentifier avec un mot de passe ou une clé publique SSH. Utiliser la méthode d'authentification que vous avez choisie pour vous connecter à la machine virtuelle.
+
--
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys#ssh-into-your-vm["Azure Docs : connexion SSH à votre machine virtuelle"^]

--
Google Cloud:: Vous ne pouvez pas spécifier de méthode d'authentification lorsque vous créez un connecteur dans Google Cloud. Vous pouvez toutefois vous connecter à l'instance de machine virtuelle Linux à l'aide de Google Cloud Console ou de Google Cloud CLI (gCloud).
+
--
https://cloud.google.com/compute/docs/instances/connecting-to-instance["Google Cloud Docs : connectez-vous aux machines virtuelles Linux"^]

--




== Modifiez l'adresse IP d'un connecteur

Vous pouvez modifier les adresses IP internes et publiques de l'instance Connector attribuées par votre fournisseur de cloud si nécessaire.

.Étapes
. Suivez les instructions de votre fournisseur de cloud pour modifier l'adresse IP locale ou l'adresse IP publique (ou les deux) de l'instance de connecteur.
. Redémarrez l'instance du connecteur pour enregistrer une nouvelle adresse IP publique avec BlueXP.
. Si vous avez modifié l'adresse IP privée, mettez à jour l'emplacement de sauvegarde des fichiers de configuration Cloud Volumes ONTAP de manière à ce que les sauvegardes soient envoyées à la nouvelle adresse IP privée sur le connecteur.
+
Mettez à jour l’emplacement de sauvegarde pour chaque système Cloud Volumes ONTAP .

+
.. Depuis l'interface de ligne de commandes de Cloud Volumes ONTAP, définir le niveau de privilège sur Advanced :
+
[source, cli]
----
set -privilege advanced
----
.. Lancer la commande suivante pour afficher la cible de sauvegarde actuelle :
+
[source, cli]
----
system configuration backup settings show
----
.. Exécutez la commande suivante pour mettre à jour l'adresse IP de la cible de sauvegarde :
+
[source, cli]
----
system configuration backup settings modify -destination <target-location>
----






== Modifier les URI d'un connecteur

Vous pouvez ajouter et supprimer l’identifiant de ressource uniforme (URI) pour un connecteur.

.Étapes
. Sélectionnez la liste déroulante *Connector* dans l'en-tête BlueXP.
. Sélectionnez *gérer les connecteurs*.
. Développez la barre *URI du connecteur* pour afficher les URI du connecteur.
. Ajoutez et supprimez des URI, puis sélectionnez *appliquer*.

