---
sidebar: sidebar 
permalink: task-upgrade-connector.html 
keywords: upgrade, manual upgrade, connector upgrade, manual connector upgrade, upgrade connector manually, private mode upgrade, offline upgrade, upgrade private mode 
summary: 'BlueXP met automatiquement à niveau un connecteur vers la dernière version lorsque vous utilisez BlueXP en mode standard ou restreint. De nouvelles versions sont généralement publiées chaque mois pour introduire de nouvelles fonctionnalités et améliorer la stabilité. Si vous préférez, vous pouvez configurer le connecteur pour extraire les mises à jour d"images à partir d"un référentiel local. Pour les déploiements en mode privé, vous devez toujours mettre à niveau manuellement le connecteur vous-même.' 
---
= Mettre à niveau un connecteur en mode privé
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si vous utilisez BlueXP en mode privé, vous pouvez mettre à niveau le connecteur dès qu'une version plus récente est disponible sur le site du support NetApp.


TIP: Lorsque vous utilisez BlueXP en mode standard ou restreint, vous n'avez pas besoin de mettre à niveau manuellement le connecteur. BlueXP met automatiquement à niveau un connecteur vers la dernière version, tant que le connecteur dispose d'un accès Internet sortant pour obtenir la mise à jour logicielle.

.Description de la tâche
Le connecteur doit redémarrer pendant le processus de mise à niveau afin que la console Web ne soit pas disponible pendant la mise à niveau.

.Étapes
. Téléchargez le logiciel du connecteur à partir du https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["Site de support NetApp"^].
+
Assurez-vous de télécharger le programme d'installation hors ligne pour les réseaux privés sans accès à Internet.

. Copiez le programme d'installation sur l'hôte Linux.
. Attribuez des autorisations pour exécuter le script.
+
[source, cli]
----
chmod +x /path/BlueXP-Connector-offline-<version>
----
+
Où <version> est la version du connecteur que vous avez téléchargé.

. Exécutez le script d'installation :
+
[source, cli]
----
sudo /path/BlueXP-Connector-offline-<version>
----
+
Où <version> est la version du connecteur que vous avez téléchargé.

. Une fois la mise à niveau terminée, vous pouvez vérifier la version du connecteur en accédant à *aide > support > connecteur*.

