---
sidebar: sidebar 
permalink: task-maintain-connectors.html 
keywords: connector operating system, connector maintenance, vm maintenance, os updates, operating system updates, stop connector, restart connector 
summary: 'La maintenance du système d"exploitation sur l"hôte du connecteur relève de votre responsabilité. Par exemple, vous devez appliquer des mises à jour de sécurité au système d"exploitation sur l"hôte du connecteur en suivant les procédures standard de votre entreprise pour la distribution du système d"exploitation.' 
---
= Maintenance de la VM connecteur et du système d'exploitation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La maintenance du système d'exploitation sur l'hôte du connecteur relève de votre responsabilité. Par exemple, vous devez appliquer des mises à jour de sécurité au système d'exploitation sur l'hôte du connecteur en suivant les procédures standard de votre entreprise pour la distribution du système d'exploitation.


TIP: Si vous disposez d'un connecteur existant, vous devez en être conscient link:reference-connector-operating-system-changes.html["Modifications apportées aux systèmes d'exploitation Linux pris en charge"].



== Correctifs du système d'exploitation et le connecteur

Vous n'avez pas besoin d'arrêter les services sur l'hôte du connecteur lors de l'application des correctifs de sécurité du système d'exploitation.



== Type de machine virtuelle ou d'instance

Si vous avez créé un connecteur directement à partir de BlueXP, BlueXP a déployé une instance de machine virtuelle dans votre fournisseur cloud à l'aide d'une configuration par défaut. Après avoir créé le connecteur, vous ne devez pas passer à une instance de machine virtuelle plus petite qui a moins de CPU ou de RAM.

Les exigences relatives au CPU et à la RAM sont les suivantes :

CPU:: 4 cœurs ou 4 CPU virtuels
RAM:: 14 GO


link:reference-connector-default-config.html["En savoir plus sur la configuration par défaut du connecteur"].



== Arrêt du démarrage de la VM connecteur

Si vous devez arrêter puis démarrer le connecteur VM, vous devez le faire depuis la console de votre fournisseur cloud ou en utilisant les procédures standard de gestion sur site.

link:concept-connectors.html#connectors-must-be-operational-at-all-times["Notez que le connecteur doit être opérationnel en permanence"].



== Connectez-vous à la machine virtuelle Linux

Si vous devez vous connecter à la machine virtuelle Linux sur laquelle s'exécute le connecteur, vous pouvez utiliser les options de connectivité disponibles auprès de votre fournisseur de cloud.

AWS:: Lorsque vous avez créé l'instance Connector dans AWS, vous avez fourni une clé d'accès AWS et une clé secrète. Vous pouvez utiliser cette paire de clés vers SSH à l'instance. Le nom d'utilisateur de l'instance EC2 Linux est ubuntu (pour les connecteurs créés avant mai 2023, le nom d'utilisateur était ec2-user).
+
--
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstances.html["AWS Docs : connectez-vous à votre instance Linux"^]

--
Azure:: Lorsque vous avez créé la machine virtuelle du connecteur dans Azure, vous avez spécifié un nom d'utilisateur et choisi de vous authentifier à l'aide d'un mot de passe ou d'une clé publique SSH. Utiliser la méthode d'authentification que vous avez choisie pour vous connecter à la machine virtuelle.
+
--
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys#ssh-into-your-vm["Azure Docs : connexion SSH à votre machine virtuelle"^]

--
Google Cloud:: Vous ne pouvez pas spécifier de méthode d'authentification lorsque vous créez un connecteur dans Google Cloud. Vous pouvez toutefois vous connecter à l'instance de machine virtuelle Linux à l'aide de Google Cloud Console ou de Google Cloud CLI (gCloud).
+
--
https://cloud.google.com/compute/docs/instances/connecting-to-instance["Google Cloud Docs : connectez-vous aux machines virtuelles Linux"^]

--




== Modifiez l'adresse IP d'un connecteur

Si votre entreprise l'exige, vous pouvez modifier l'adresse IP interne et l'adresse IP publique de l'instance de connecteur qui est automatiquement attribuée par votre fournisseur de cloud.

.Étapes
. Suivez les instructions de votre fournisseur de cloud pour modifier l'adresse IP locale ou l'adresse IP publique (ou les deux) de l'instance de connecteur.
. Si vous avez modifié l'adresse IP publique et que vous devez vous connecter à l'interface utilisateur locale s'exécutant sur le connecteur, redémarrez l'instance de connecteur pour enregistrer la nouvelle adresse IP avec BlueXP.
. Si vous avez modifié l'adresse IP privée, mettez à jour l'emplacement de sauvegarde des fichiers de configuration Cloud Volumes ONTAP de manière à ce que les sauvegardes soient envoyées à la nouvelle adresse IP privée sur le connecteur.
+
Vous devez mettre à jour l'emplacement de sauvegarde de chaque système Cloud Volumes ONTAP.

+
.. Lancer la commande suivante depuis l'interface de ligne de commandes de Cloud Volumes ONTAP pour afficher la cible de sauvegarde actuelle :
+
[source, cli]
----
system configuration backup show
----
.. Exécutez la commande suivante pour mettre à jour l'adresse IP de la cible de sauvegarde :
+
[source, cli]
----
system configuration backup settings modify -destination <target-location>
----






== Modifier les URI d'un connecteur

Ajoutez et supprimez l'URI (Uniform Resource identifier) d'un connecteur.

.Étapes
. Sélectionnez la liste déroulante *Connector* dans l'en-tête BlueXP.
. Sélectionnez *gérer les connecteurs*.
. Sélectionnez le menu d'action d'un connecteur et sélectionnez *Modifier les URI*.
. Ajoutez et supprimez des URI, puis sélectionnez *appliquer*.

