---
sidebar: sidebar 
permalink: task-provide-permissions-google.html 
keywords: google cloud permissions, permissions, gcp permissions, service account, gcp service account 
summary: Si vous avez installé manuellement le logiciel Connector sur votre propre hôte Linux, vous devez fournir à BlueXP les autorisations que vous avez précédemment configurées. Si vous disposez des autorisations requises, BlueXP peut gérer vos données et votre infrastructure de stockage dans Google Cloud. 
---
= Offrez des autorisations Google Cloud à BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si vous avez installé manuellement le logiciel Connector sur votre propre hôte Linux, vous devez fournir à BlueXP les autorisations que vous avez précédemment configurées. Si vous disposez des autorisations requises, BlueXP peut gérer vos données et votre infrastructure de stockage dans Google Cloud.

link:task-set-up-permissions-google.html["Découvrez comment configurer ces autorisations"].

Ces étapes ne s'appliquent pas si vous avez déployé le connecteur directement à partir de BlueXP ou à l'aide de gcloud.

.Étapes
. Accédez au portail Google Cloud et attribuez le compte de service à l'instance de la VM Connector.
+
https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes["Documentation Google Cloud : modification du compte de service et des étendues d'accès pour une instance"^]

. Si vous souhaitez déployer Cloud Volumes ONTAP dans d'autres projets, autorisez l'accès en ajoutant le compte de service doté du rôle BlueXP à ce projet. Vous devrez répéter cette étape pour chaque projet.


.Résultat
BlueXP dispose désormais des autorisations dont il a besoin pour effectuer des actions en votre nom dans Google Cloud.
