---
sidebar: sidebar 
permalink: task-logging-in.html 
keywords: logging in, log in, sign in, signing in, cloud central, netapp cloud central, user account, federated, federation, federated login, federation login, login with netapp, log in with netapp, sign up, create account 
summary: 'Une fois inscrit à BlueXP, vous pouvez vous connecter à partir de votre navigateur Web via l"interface utilisateur SaaS.' 
---
= Connectez-vous à BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Une fois inscrit à BlueXP, vous pouvez vous connecter à partir de votre navigateur Web via l'interface utilisateur SaaS.

link:task-sign-up-saas.html["Découvrez comment vous inscrire à BlueXP et créer une organisation"].

Si vous accédez à BlueXP à partir d'une région gouvernementale ou d'un site qui n'a pas d'accès Internet sortant, vous devez vous connecter à l'interface utilisateur BlueXP qui fonctionne localement sur le connecteur. link:task-managing-connectors.html#access-the-local-ui["Découvrez comment accéder à l'interface utilisateur locale sur le connecteur"].

.Options de connexion
Vous pouvez vous connecter à BlueXP à l'aide de l'une des options suivantes :

* Vos identifiants existants du site de support NetApp (NSS)
* Un identifiant NetApp Cloud avec votre adresse e-mail et un mot de passe
* Une connexion fédérée
+
Vous pouvez utiliser l'authentification unique pour vous connecter à l'aide des informations d'identification de votre annuaire d'entreprise (identité fédérée). Pour en savoir plus, consultez le https://cloud.netapp.com/help-center["Centre d'aide BlueXP"^] puis cliquez sur *options de connexion*.



.Étapes
. Ouvrez un navigateur Web et accédez au https://console.bluexp.netapp.com["Console BlueXP"^]
. Sur la page *connexion*, entrez l'adresse e-mail associée à votre connexion.
. En fonction de la méthode d'authentification associée à votre connexion, vous serez invité à saisir vos informations d'identification :
+
** Identifiants cloud NetApp : saisissez votre mot de passe
** Utilisateur fédéré : saisissez vos informations d'identification fédérées
** Entrez votre compte sur le site de support NetApp : saisissez vos identifiants du site de support NetApp




.Résultat
Vous êtes maintenant connecté et pouvez commencer à utiliser BlueXP pour gérer votre infrastructure multicloud hybride.
