---
sidebar: sidebar 
permalink: task-install-connector-google-manual.html 
keywords: install connector, google cloud connector installation, google cloud connector, install connector in google cloud, bluexp, gcloud, manual install, create connector, gcp installation, gcp connector 
summary: 'Pour installer manuellement le connecteur sur votre propre hôte Linux, vous devez vérifier la configuration requise pour l"hôte, configurer votre réseau, préparer les autorisations Google Cloud, activer les API Google Cloud, installer le connecteur, puis fournir les autorisations que vous avez préparées.' 
---
= Installez manuellement le connecteur dans Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Pour installer manuellement le connecteur sur votre propre hôte Linux, vous devez vérifier la configuration requise pour l'hôte, configurer votre réseau, préparer les autorisations Google Cloud, activer les API Google Cloud, installer le connecteur, puis fournir les autorisations que vous avez préparées.

.Avant de commencer
Vous devriez passer en revue link:reference-limitations.html["Limitations du connecteur"].



== Étape 1 : vérifiez la configuration requise pour l'hôte

Le logiciel du connecteur doit être exécuté sur un hôte qui répond à des exigences spécifiques du système d'exploitation, de la RAM, des ports, etc.

Hôte dédié:: Le connecteur n'est pas pris en charge sur un hôte partagé avec d'autres applications. L'hôte doit être un hôte dédié.
Systèmes d'exploitation pris en charge::
+
--
* Ubuntu 22.04
* CentOS 7.6, 7.7, 7.8 et 7.9
* Red Hat Enterprise Linux 7.6, 7.7, 7.8 et 7.9
+
L'hôte doit être enregistré auprès de Red Hat Subscription Management. S'il n'est pas enregistré, l'hôte ne peut pas accéder aux référentiels pour mettre à jour les logiciels tiers requis lors de l'installation du connecteur.

+
Le connecteur est pris en charge sur les versions en anglais de ces systèmes d'exploitation.



--
Hyperviseur:: Un hyperviseur bare Metal ou hébergé certifié pour exécuter Ubuntu, CentOS ou Red Hat Enterprise Linux est requis.
+
--
https://access.redhat.com/certified-hypervisors["Solution Red Hat : quels hyperviseurs sont certifiés pour l'exécution de Red Hat Enterprise Linux ?"^]

--
CPU:: 4 cœurs ou 4 CPU virtuels
RAM:: 14 GO
Type de machine Google Cloud:: Type d'instance qui répond aux exigences relatives au CPU et à la RAM indiquées ci-dessus. Nous recommandons n2-standard-4.
+
--
Ce connecteur est pris en charge dans Google Cloud sur une instance de machine virtuelle avec un système d'exploitation pris en charge https://cloud.google.com/compute/shielded-vm/docs/shielded-vm["Fonctionnalités MV blindées"^]

--
Espace disque dans /opt:: 100 Gio d'espace doit être disponible
Espace disque dans /var:: 20 Gio d'espace doit être disponible
Moteur Docker:: Docker Engine version 19.3.1 ou ultérieure est requis sur l'hôte avant d'installer le connecteur. https://docs.docker.com/engine/install/["Voir les instructions d'installation"^]




== Étape 2 : configuration du réseau

Configurez votre réseau de manière à ce que Connector puisse gérer les ressources et les processus dans votre environnement de cloud hybride. Par exemple, vous devez vous assurer que les connexions sont disponibles pour les réseaux cibles et que l'accès Internet sortant est disponible.

Connexions aux réseaux cibles:: Un connecteur nécessite une connexion réseau à l'emplacement où vous prévoyez de créer et de gérer des environnements de travail. Par exemple, le réseau sur lequel vous prévoyez de créer des systèmes Cloud Volumes ONTAP ou un système de stockage dans votre environnement sur site.


Accès Internet sortant:: L'emplacement réseau où vous déployez le connecteur doit disposer d'une connexion Internet sortante pour contacter des points finaux spécifiques.


Points finaux contactés lors de l'installation manuelle:: Lorsque vous installez manuellement le connecteur sur votre propre hôte Linux, le programme d'installation du connecteur nécessite l'accès aux URL suivantes pendant le processus d'installation :
+
--
* \https://support.netapp.com
* \https://mysupport.netapp.com
* \https://cloudmanager.cloud.netapp.com/tenancy
* \https://stream.cloudmanager.cloud.netapp.com
* \https://production-artifacts.cloudmanager.cloud.netapp.com
* \https://*.blob.core.windows.net
* \https://cloudmanagerinfraprod.azurecr.io
+
L'hôte peut essayer de mettre à jour les packages du système d'exploitation lors de l'installation. L'hôte peut contacter différents sites de mise en miroir pour ces packages OS.



--


Points d'extrémité contactés depuis le connecteur:: Le connecteur nécessite un accès Internet sortant pour contacter les terminaux suivants afin de gérer les ressources et les processus au sein de votre environnement de cloud public pour les opérations quotidiennes.
+
--
[cols="2a,1a"]
|===
| Terminaux | Objectif 


 a| 
\https://www.googleapis.com/compute/v1/
\https://compute.googleapis.com/compute/v1
\https://cloudresourcemanager.googleapis.com/v1/projects
\https://www.googleapis.com/compute/beta
\https://storage.googleapis.com/storage/v1
\https://www.googleapis.com/storage/v1
\https://iam.googleapis.com/v1
\https://cloudkms.googleapis.com/v1
\https://www.googleapis.com/deploymentmanager/v2/projects
 a| 
De gérer des ressources dans Google Cloud.



 a| 
\https://support.netapp.com
 a| 
Pour obtenir des informations sur les licences et envoyer des messages AutoSupport au support NetApp.



 a| 
\https://*.api.bluexp.netapp.com

\https://api.bluexp.netapp.com

\https://*.cloudmanager.cloud.netapp.com

\https://cloudmanager.cloud.netapp.com

\https://netapp-cloud-account.auth0.com
 a| 
Pour fournir des fonctions et des services SaaS dans BlueXP.

Notez que le connecteur est actuellement en contact avec « cloudmanager.cloud.netapp.com", mais il commencera à contacter « api.bluexp.netapp.com" dans une prochaine version.



 a| 
\https://*.blob.core.windows.net

\https://cloudmanagerinfraprod.azurecr.io
 a| 
Pour mettre à niveau le connecteur et ses composants Docker.

|===
--


Serveur proxy:: Si votre organisation nécessite le déploiement d'un serveur proxy pour tout le trafic Internet sortant, procurez-vous les informations suivantes sur votre proxy HTTP ou HTTPS. Vous devrez fournir ces informations pendant l'installation.
+
--
* Adresse IP
* Informations d'identification
* Certificat HTTPS


--


Ports:: Il n'y a pas de trafic entrant vers le connecteur, sauf si vous l'initiez ou si le connecteur est utilisé comme proxy pour envoyer des messages AutoSupport de Cloud Volumes ONTAP au support NetApp.
+
--
* HTTP (80) et HTTPS (443) permettent d'accéder à l'interface utilisateur locale que vous utiliserez dans de rares circonstances.
* SSH (22) n'est nécessaire que si vous devez vous connecter à l'hôte pour le dépannage.
* Les connexions entrantes via le port 3128 sont requises si vous déployez des systèmes Cloud Volumes ONTAP dans un sous-réseau où aucune connexion Internet sortante n'est disponible.
+
Si les systèmes Cloud Volumes ONTAP ne disposent pas d'une connexion Internet sortante pour envoyer des messages AutoSupport, BlueXP les configure automatiquement pour qu'ils utilisent un serveur proxy inclus avec le connecteur. La seule condition est de s'assurer que le groupe de sécurité du connecteur autorise les connexions entrantes sur le port 3128. Vous devrez ouvrir ce port après le déploiement du connecteur.



--




== Étape 3 : définissez les autorisations pour le connecteur

Un compte de service Google Cloud est requis pour fournir le connecteur avec les autorisations dont BlueXP a besoin pour gérer les ressources dans Google Cloud. Lorsque vous créez le connecteur, vous devez associer ce compte de service à la machine virtuelle Connector.

.Étapes
. Créez un rôle personnalisé dans Google Cloud :
+
.. Créez un fichier YAML qui inclut le contenu du link:reference-permissions-gcp.html["Autorisations de compte de service pour le connecteur"].
.. Dans Google Cloud, activez le shell cloud.
.. Téléchargez le fichier YAML qui inclut les autorisations requises.
.. Créez un rôle personnalisé à l'aide de `gcloud iam roles create` commande.
+
L'exemple suivant crée un rôle nommé « connecteur » au niveau du projet :

+
`gcloud iam roles create connector --project=myproject --file=connector.yaml`

+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Documents Google Cloud : création et gestion de rôles personnalisés"^]



. Créer un compte de service dans Google Cloud et attribuer le rôle au compte de service :
+
.. Dans le service IAM & Admin, sélectionnez *comptes de service > Créer un compte de service*.
.. Entrez les détails du compte de service et sélectionnez *Créer et continuer*.
.. Sélectionnez le rôle que vous venez de créer.
.. Terminez les étapes restantes pour créer le rôle.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Documents Google Cloud : création d'un compte de service"^]



. Si vous prévoyez de déployer des systèmes Cloud Volumes ONTAP dans différents projets que le projet sur lequel réside le connecteur, vous devrez fournir au compte de service du connecteur l'accès à ces projets.
+
Disons, par exemple, que le connecteur est dans le projet 1 et que vous voulez créer des systèmes Cloud Volumes ONTAP dans le projet 2. Vous devrez accorder l'accès au compte de service dans le projet 2.

+
.. Dans le service IAM & Admin, sélectionnez le projet Google Cloud où vous souhaitez créer les systèmes Cloud Volumes ONTAP.
.. Sur la page *IAM*, sélectionnez *accorder accès* et fournissez les détails nécessaires.
+
*** Saisissez l'e-mail du compte de service du connecteur.
*** Sélectionnez le rôle personnalisé du connecteur.
*** Sélectionnez *Enregistrer*.




+
Pour plus de détails, reportez-vous à https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role["Documentation Google Cloud"^]



.Résultat
Le compte de service de la machine virtuelle Connector est configuré.



== Étape 4 : configuration des autorisations VPC partagées

Si vous utilisez un VPC partagé pour déployer des ressources dans un projet de service, vous devrez préparer vos autorisations.

Ce tableau est fourni à titre de référence et votre environnement doit refléter la table des autorisations lorsque la configuration IAM est terminée.

.Afficher les autorisations VPC partagées
[%collapsible]
====
[cols="10,10,10,18,18,34"]
|===
| Identité | Créateur | Hébergé dans | Autorisations de projet de service | Autorisations de projet hôte | Objectif 


| Compte Google pour déployer le connecteur | Personnalisées | Projet de service  a| 
link:task-install-connector-google-bluexp-gcloud.html#step-2-set-up-permissions-to-create-the-connector["Stratégie de déploiement de connecteur"]
 a| 
compute.networkUser
| Déploiement du connecteur dans le projet de service 


| Connecteur de compte de service | Personnalisées | Projet de service  a| 
link:reference-permissions-gcp.html["Stratégie de compte de service de connecteur"]
| compute.networkUser

deploymentmanager.editor | Déploiement et maintenance de Cloud Volumes ONTAP et des services dans le projet de service 


| Compte de service Cloud Volumes ONTAP | Personnalisées | Projet de service | storage.admin

Membre: Compte de service BlueXP à partir de serviceAccount.user | S/O | (Facultatif) pour le Tiering des données et la sauvegarde et la restauration BlueXP 


| Agent de service Google API | Google Cloud | Projet de service  a| 
Editeur (par défaut)
 a| 
compute.networkUser
| Interagit avec les API Google Cloud pour le compte du déploiement. Permet à BlueXP d'utiliser le réseau partagé. 


| Compte de service par défaut Google Compute Engine | Google Cloud | Projet de service  a| 
Editeur (par défaut)
 a| 
compute.networkUser
| Déploie les instances Google Cloud et l'infrastructure de calcul pour le compte du déploiement. Permet à BlueXP d'utiliser le réseau partagé. 
|===
Remarques :

. deploymentmanager.Editor est uniquement requis au niveau du projet hôte si vous ne passez pas de règles de pare-feu au déploiement et que vous choisissez de laisser BlueXP les créer pour vous. BlueXP créera un déploiement dans le projet hôte qui contient la règle de pare-feu VPC0 si aucune règle n'est spécifiée.
. Firewall.create et firewall.delete ne sont nécessaires que si vous ne passez pas de règles de pare-feu au déploiement et que vous choisissez de laisser BlueXP les créer pour vous. Ces autorisations résident dans le fichier .yaml du compte BlueXP. Si vous déployez une paire HA à l'aide d'un VPC partagé, ces autorisations seront utilisées pour créer les règles de pare-feu pour VPC1, 2 et 3. Pour tous les autres déploiements, ces autorisations seront également utilisées pour créer des règles pour VPC0.
. Pour le Tiering des données, le compte de service de Tiering doit avoir le rôle serviceAccount.user sur le compte de service, et pas seulement au niveau du projet. Actuellement, si vous attribuez serviceAccount.user au niveau du projet, les autorisations ne s'affichent pas lorsque vous interrogez le compte de service avec getIAMPolicy.


====


== Étape 5 : activez les API Google Cloud

Vous devez activer plusieurs API Google Cloud avant de pouvoir déployer les systèmes Cloud Volumes ONTAP dans Google Cloud.

.Étape
. Activez les API Google Cloud suivantes dans votre projet :
+
** API Cloud Deployment Manager V2
** API de journalisation cloud
** API Cloud Resource Manager
** API du moteur de calcul
** API de gestion des identités et des accès
** API KMS (Cloud Key Management Service
+
(Requis uniquement si vous prévoyez d'utiliser la sauvegarde et la restauration BlueXP avec des clés de chiffrement gérées par le client (CMEK))





https://cloud.google.com/apis/docs/getting-started#enabling_apis["Documentation Google Cloud : activation des API"^]



== Étape 6 : installez le connecteur

Une fois la configuration requise terminée, vous pouvez installer manuellement le logiciel sur votre propre hôte Linux.

.Avant de commencer
Vous devez disposer des éléments suivants :

* Privilèges root pour installer le connecteur.
* Détails sur un serveur proxy, si un proxy est requis pour accéder à Internet à partir du connecteur.
+
Vous avez la possibilité de configurer un serveur proxy après l'installation, mais cela nécessite de redémarrer le connecteur.

* Un certificat signé par une autorité de certification, si le serveur proxy utilise HTTPS ou si le proxy est un proxy interceptant.


.Description de la tâche
Le programme d'installation disponible sur le site du support NetApp peut être une version antérieure. Après l'installation, le connecteur se met automatiquement à jour si une nouvelle version est disponible.

.Étapes
. Vérifiez que docker est activé et exécuté.
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----
. Si les variables système _http_proxy_ ou _https_proxy_ sont définies sur l'hôte, supprimez-les :
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
Si vous ne supprimez pas ces variables système, l'installation échouera.

. Téléchargez le logiciel du connecteur à partir du https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["Site de support NetApp"^], Puis copiez-le sur l'hôte Linux.
+
Vous devez télécharger le programme d'installation du connecteur « en ligne » destiné à être utilisé sur votre réseau ou dans le cloud. Un programme d'installation séparé « hors ligne » est disponible pour le connecteur, mais il n'est pris en charge que pour les déploiements en mode privé.

. Attribuez des autorisations pour exécuter le script.
+
[source, cli]
----
chmod +x Cloud-Manager-Connector-Cloud-<version>
----
+
Où <version> est la version du connecteur que vous avez téléchargé.

. Exécutez le script d'installation.
+
[source, cli]
----
 ./Cloud-Manager-Connector-Cloud-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
Les paramètres --proxy et --cacert sont facultatifs. Si vous disposez d'un serveur proxy, vous devez entrer les paramètres comme indiqué. Le programme d'installation ne vous invite pas à fournir des informations sur un proxy.

+
Voici un exemple de commande utilisant les deux paramètres facultatifs :

+
[source, cli]
----
 ./Cloud-Manager-Connector-Cloud-V3.9.32 --proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
--proxy configure le connecteur pour utiliser un serveur proxy HTTP ou HTTPS à l'aide de l'un des formats suivants :

+
** \http://address:port
** \http://user-name:password@address:port
** \http://domain-name%92user-name:password@address:port
** \https://address:port
** \https://user-name:password@address:port
** \https://domain-name%92user-name:password@address:port
+
Notez ce qui suit :

+
*** L'utilisateur peut être un utilisateur local ou un utilisateur de domaine.
*** Pour un utilisateur de domaine, vous devez utiliser le code ASCII du \ comme indiqué ci-dessus.
*** BlueXP ne prend pas en charge les mots de passe comprenant le caractère @.




+
--cacert spécifie un certificat signé par une autorité de certification à utiliser pour l'accès HTTPS entre le connecteur et le serveur proxy. Ce paramètre est requis uniquement si vous spécifiez un serveur proxy HTTPS ou si le proxy est un proxy interceptant.

. Attendez la fin de l'installation.
+
À la fin de l'installation, le service connecteur (ocm) redémarre deux fois si vous avez spécifié un serveur proxy.

. Ouvrez un navigateur Web à partir d'un hôte connecté à la machine virtuelle Connector et entrez l'URL suivante :
+
https://_ipaddress_[]

. Une fois connecté, configurez le connecteur :
+
.. Spécifiez le compte BlueXP à associer au connecteur.
.. Entrez un nom pour le système.
.. Sous *exécutez-vous dans un environnement sécurisé ?* maintenez le mode restreint désactivé.
+
Vous devez désactiver le mode restreint, car ces étapes décrivent l'utilisation de BlueXP en mode standard. Vous devez activer le mode restreint uniquement si vous disposez d'un environnement sécurisé et souhaitez déconnecter ce compte des services back-end BlueXP. Si c'est le cas, link:task-quick-start-restricted-mode.html["Suivez les étapes pour démarrer avec BlueXP en mode restreint"].

.. Sélectionnez *commençons*.




.Résultat
Le connecteur est maintenant installé et configuré avec votre compte BlueXP.



== Étape 7 : fournissez des autorisations à BlueXP

Vous devez fournir à BlueXP les autorisations Google Cloud que vous avez précédemment configurées. Si vous disposez des autorisations requises, BlueXP peut gérer vos données et votre infrastructure de stockage dans Google Cloud.

.Étapes
. Accédez au portail Google Cloud et attribuez le compte de service à l'instance de la VM Connector.
+
https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes["Documentation Google Cloud : modification du compte de service et des étendues d'accès pour une instance"^]

. Si vous souhaitez gérer des ressources dans d'autres projets Google Cloud, autorisez l'accès en ajoutant le compte de service doté du rôle BlueXP à ce projet. Vous devrez répéter cette étape pour chaque projet.


.Résultat
BlueXP dispose désormais des autorisations dont il a besoin pour effectuer des actions en votre nom dans Google Cloud.
