---
sidebar: sidebar 
permalink: task-install-connector-on-prem.html 
keywords: install connector, on prem connector installation, on prem connector, install connector on prem, manual install 
summary: 'Installez un connecteur sur site, puis connectez-vous et configurez-le pour qu"il fonctionne avec votre compte BlueXP.' 
---
= Installez et configurez un connecteur sur site
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Installez un connecteur sur site, puis connectez-vous et configurez-le pour qu'il fonctionne avec votre compte BlueXP.



== Poser le connecteur

Téléchargez et installez le logiciel Connector sur un hôte Linux existant sur site.

.Avant de commencer
Vous devez disposer des éléments suivants :

* Privilèges root pour installer le connecteur.
* Détails sur un serveur proxy, si un proxy est requis pour accéder à Internet à partir du connecteur.
+
Vous avez la possibilité de configurer un serveur proxy après l'installation, mais cela nécessite de redémarrer le connecteur.

* Un certificat signé par une autorité de certification, si le serveur proxy utilise HTTPS ou si le proxy est un proxy interceptant.


.Description de la tâche
Le programme d'installation disponible sur le site du support NetApp peut être une version antérieure. Après l'installation, le connecteur se met automatiquement à jour si une nouvelle version est disponible.

.Étapes
. Vérifiez que docker est activé et exécuté.
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----
. Si les variables système _http_proxy_ ou _https_proxy_ sont définies sur l'hôte, supprimez-les :
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
Si vous ne supprimez pas ces variables système, l'installation échouera.

. Téléchargez le logiciel du connecteur à partir du https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["Site de support NetApp"^], Puis copiez-le sur l'hôte Linux.
+
Vous devez télécharger le programme d'installation du connecteur « en ligne » destiné à être utilisé sur votre réseau ou dans le cloud. Un programme d'installation séparé « hors ligne » est disponible pour le connecteur, mais il n'est pris en charge que pour les déploiements en mode privé.

. Attribuez des autorisations pour exécuter le script.
+
[source, cli]
----
chmod +x OnCommandCloudManager-<version>
----
+
Où <version> est la version du connecteur que vous avez téléchargé.

. Exécutez le script d'installation.
+
[source, cli]
----
 ./OnCommandCloudManager-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
Les paramètres --proxy et --cacert sont facultatifs. Si vous disposez d'un serveur proxy, vous devez entrer le ou les paramètres comme indiqué. Le programme d'installation ne vous invite pas à fournir des informations sur un proxy.

+
Voici un exemple de commande utilisant les deux paramètres facultatifs :

+
[source, cli]
----
 ./OnCommandCloudManager-V3.9.26 --proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
--proxy configure le connecteur pour utiliser un serveur proxy HTTP ou HTTPS à l'aide de l'un des formats suivants :

+
** \http://address:port
** \http://username:password@address:port
** \https://address:port
** \https://username:password@address:port
+
L'utilisateur doit être un utilisateur local. Les utilisateurs du domaine ne sont pas pris en charge.



+
--cacert spécifie un certificat signé par une autorité de certification à utiliser pour l'accès HTTPS entre le connecteur et le serveur proxy. Ce paramètre est requis uniquement si vous spécifiez un serveur proxy HTTPS ou si le proxy est un proxy interceptant.



.Résultat
Le connecteur est maintenant installé. À la fin de l'installation, le service connecteur (ocm) redémarre deux fois si vous avez spécifié un serveur proxy.



== Configurer le connecteur

Inscrivez-vous ou connectez-vous, puis configurez le connecteur pour qu'il fonctionne avec votre compte.

.Étapes
. Ouvrez un navigateur Web et entrez l'URL suivante :
+
https://_ipaddress_[]

+
_Ipaddress_ peut être localhost, une adresse IP privée ou une adresse IP publique, selon la configuration de l'hôte. Par exemple, si le connecteur est dans le Cloud public sans adresse IP publique, vous devez entrer une adresse IP privée à partir d'un hôte qui a une connexion à l'hôte du connecteur.

. S'inscrire ou se connecter.
. Une fois connecté, configurez BlueXP :
+
.. Spécifiez le compte BlueXP à associer au connecteur.
.. Entrez un nom pour le système.
.. Sous *exécutez-vous dans un environnement sécurisé ?* maintenez le mode restreint désactivé.
+
Vous devez désactiver le mode restreint, car ces étapes décrivent l'utilisation de BlueXP en mode standard. (En outre, le mode restreint n'est pas pris en charge lorsque le connecteur est installé sur site.)

.. Sélectionnez *commençons*.




.Résultat
BlueXP est maintenant configuré avec le connecteur que vous venez d'installer.

.Et la suite ?
link:task-provide-permissions-on-prem.html["Fournissez à BlueXP les autorisations que vous avez précédemment configurées"].
