---
sidebar: sidebar 
permalink: task-logging-in.html 
keywords: logging in, log in, sign in, signing in, cloud central, netapp cloud central, user account, federated, federation, federated login, federation login, login with netapp, log in with netapp, sign up, create account 
summary: Une fois que vous vous êtes inscrit à BlueXP, vous pouvez vous connecter à partir de votre navigateur web via la console web. 
---
= Se connecter à BlueXP (mode standard)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Une fois que vous vous êtes inscrit à BlueXP, vous pouvez vous connecter à partir de la console web.

.Options de connexion
Vous pouvez vous connecter à la console Web BlueXP à l'aide de l'une des options suivantes :

* Vos identifiants existants du site de support NetApp (NSS)
* Un identifiant NetApp Cloud avec votre adresse e-mail et un mot de passe
* Une connexion fédérée
+
Vous pouvez utiliser l'authentification unique pour vous connecter à l'aide des informations d'identification de votre annuaire d'entreprise (identité fédérée). link:concept-federation.html["Découvrez comment utiliser la fédération des identités avec BlueXP"].



.Étapes
. Ouvrez un navigateur Web et accédez au https://console.bluexp.netapp.com["Console BlueXP"^]
. Sur la page *connexion*, entrez l'adresse e-mail associée à votre connexion.
. En fonction de la méthode d'authentification associée à votre connexion, vous serez invité à saisir vos informations d'identification :
+
** Identifiants cloud NetApp : saisissez votre mot de passe
** Utilisateur fédéré : saisissez vos informations d'identification fédérées
** Entrez votre compte sur le site de support NetApp : saisissez vos identifiants du site de support NetApp




.Résultat
Vous êtes maintenant connecté et pouvez commencer à utiliser BlueXP pour gérer votre infrastructure multicloud hybride.
