= Connecteur 3.9.52
:allow-uri-read: 




=== Connecteur 3.9.52

Cette version de BlueXP  Connector inclut des améliorations mineures de la sécurité et des correctifs de bogues, ainsi que quelques mises à jour supplémentaires.

À ce stade, la version 3.9.52 est disponible pour le mode standard et le mode restreint.



==== Prise en charge de Docker 27 et Docker 28

Docker 27 et Docker 28 sont désormais pris en charge avec le connecteur.



==== Cloud Volumes ONTAP

Les nœuds Cloud Volumes ONTAP ne s'arrêtent plus lorsque le connecteur est hors conformité ou hors service pendant plus de 14 jours. Cloud Volumes ONTAP continue d'envoyer des messages de gestion des événements en cas de perte d'accès au connecteur. Cette modification vise à garantir que Cloud Volumes ONTAP puisse continuer à fonctionner même en cas d'interruption prolongée du connecteur. Elle ne modifie pas les exigences de conformité du connecteur.



=== Administration Keystone disponible dans BlueXP 

La version bêta de NetApp Keystone dans BlueXP  a permis d'accéder à l'administration Keystone. Vous pouvez accéder à la page d'inscription de la version bêta de NetApp Keystone à partir de la barre de navigation de gauche de BlueXP .



=== Gestion des identités et des accès BlueXP 



==== Nouveaux rôles de gestion du stockage

Les rôles d’administrateur de stockage, de spécialiste de l’état du système et de visualiseur de stockage sont disponibles et peuvent être attribués aux utilisateurs.

Ces rôles vous permettent de gérer qui dans votre organisation peut découvrir et gérer les ressources de stockage, ainsi que d'afficher les informations sur l'état du stockage et d'effectuer des mises à jour logicielles.

Ces rôles sont pris en charge pour contrôler l'accès aux ressources de stockage suivantes :

* Systèmes E-Series
* Systèmes StorageGRID
* Systèmes ONTAP sur site


Vous pouvez également utiliser ces rôles pour contrôler l’accès aux services BlueXP suivants :

* Mises à jour de logiciels
* Conseiller digital
* Résilience opérationnelle
* Efficacité économique
* Durabilité


Les rôles suivants ont été ajoutés :

* *Administrateur de stockage*
+
Administrer l'intégrité, la gouvernance et la découverte du stockage des ressources de l'organisation. Ce rôle peut également effectuer des mises à jour logicielles sur les ressources de stockage.

* *Spécialiste de la santé du système*
+
Administrer l'intégrité et la gouvernance du stockage des ressources de l'organisation. Ce rôle peut également effectuer des mises à jour logicielles sur les ressources de stockage. Il ne peut pas modifier ni supprimer les environnements de travail.

* *Visionneuse de stockage*
+
Afficher les informations sur l’état du stockage et les données de gouvernance.

+
link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès."^]


