= Connecteur 3.9.51
:allow-uri-read: 




=== Connecteur 3.9.51

Cette version de BlueXP Connector inclut des améliorations mineures de la sécurité et des correctifs.

À ce stade, la version 3.9.51 est disponible pour le mode standard et le mode restreint.



=== Gestion des identités et des accès BlueXP 

* Pour accéder à la protection contre les ransomware, les utilisateurs ne disposant pas d'un rôle d'administrateur d'organisation ou de dossier ou de projet doivent se voir attribuer un rôle de protection contre les ransomwares. Vous pouvez attribuer un utilisateur à l'un des deux rôles suivants : administrateur de la protection contre les ransomware ou visualiseur de la protection contre les ransomware.
* Les utilisateurs ne disposant pas d'un administrateur Org, d'un dossier ou d'un administrateur de projet doivent se voir attribuer un rôle Keystone pour avoir accès à Keystone. Vous pouvez attribuer un utilisateur à l'un des deux rôles suivants : admin Keystone ou visionneur Keystone.


link:https://docs.netapp.com/reference-iam-predefined-roles.html["Découvrez les nouveaux rôles."^]

* Si vous disposez du rôle d'administrateur Org, dossier ou projet, vous pouvez désormais associer un abonnement Keystone à un projet IAM. L'association d'un abonnement Keystone à un projet IAM vous permet de contrôler l'accès à Keystone dans BlueXP .

