= Connecteur 3.9.52
:allow-uri-read: 




=== Connecteur 3.9.52

Cette version de BlueXP  Connector inclut des améliorations mineures de la sécurité et des correctifs de bogues, ainsi que quelques mises à jour supplémentaires.

À ce stade, la version 3.9.52 est disponible pour le mode standard et le mode restreint.



==== Prise en charge de Docker 27 et Docker 28

Docker 27 et Docker 28 sont désormais pris en charge avec le connecteur.



==== Cloud Volumes ONTAP

Les nœuds basés sur la capacité de Cloud Volumes ONTAP ne s'arrêtent plus lorsque le connecteur n'est pas conforme ou est en panne pendant plus de 14 jours. Cloud Volumes ONTAP continue d'envoyer des messages de gestion des événements en cas de perte d'accès au connecteur. Cette modification vise à garantir que Cloud Volumes ONTAP puisse continuer à fonctionner même en cas d'interruption prolongée du connecteur. Elle ne modifie pas les exigences de conformité du connecteur.



=== Administration Keystone disponible dans BlueXP 

La version bêta de NetApp Keystone dans BlueXP  a permis d'accéder à l'administration Keystone. Vous pouvez accéder à la page d'inscription de la version bêta de NetApp Keystone à partir de la barre de navigation de gauche de BlueXP .



=== Gestion des identités et des accès BlueXP 

Les nouvelles fonctionnalités suivantes sont disponibles dans BlueXP IAM.



==== Authentification multifacteur (MFA) pour les utilisateurs locaux

Les utilisateurs locaux (non fédérés et non associés à un compte de site de support NetApp) peuvent activer l'authentification multifacteur. Les administrateurs peuvent gérer les paramètres d'authentification multifacteur des utilisateurs, notamment les désactiver temporairement ou les supprimer si nécessaire.
