= 
:allow-uri-read: 


Si vous utilisez un VPC partagé pour déployer des ressources dans un projet de service, vous devrez préparer vos autorisations.

Ce tableau est fourni à titre de référence et votre environnement doit refléter la table des autorisations lorsque la configuration IAM est terminée.

.Afficher les autorisations VPC partagées
[%collapsible]
====
[cols="10,10,10,18,18,34"]
|===
| Identité | Créateur | Hébergé dans | Autorisations de projet de service | Autorisations de projet hôte | Objectif 


| Compte Google pour déployer le connecteur | Personnalisées | Projet de service  a| 
link:task-install-connector-google-bluexp-gcloud.html#step-2-set-up-permissions-to-create-the-connector["Stratégie de déploiement de connecteur"]
 a| 
compute.networkUser
| Déploiement du connecteur dans le projet de service 


| Connecteur de compte de service | Personnalisées | Projet de service  a| 
link:reference-permissions-gcp.html["Stratégie de compte de service de connecteur"]
| compute.networkUser

deploymentmanager.editor | Déploiement et maintenance de Cloud Volumes ONTAP et des services dans le projet de service 


| Compte de service Cloud Volumes ONTAP | Personnalisées | Projet de service | storage.admin

Membre: Compte de service BlueXP à partir de serviceAccount.user | S/O | (Facultatif) pour le Tiering des données et la sauvegarde et la restauration BlueXP 


| Agent de service Google API | Google Cloud | Projet de service  a| 
Editeur (par défaut)
 a| 
compute.networkUser
| Interagit avec les API Google Cloud pour le compte du déploiement. Permet à BlueXP d'utiliser le réseau partagé. 


| Compte de service par défaut Google Compute Engine | Google Cloud | Projet de service  a| 
Editeur (par défaut)
 a| 
compute.networkUser
| Déploie les instances Google Cloud et l'infrastructure de calcul pour le compte du déploiement. Permet à BlueXP d'utiliser le réseau partagé. 
|===
Remarques :

. deploymentmanager.Editor est uniquement requis au niveau du projet hôte si vous ne passez pas de règles de pare-feu au déploiement et que vous choisissez de laisser BlueXP les créer pour vous. BlueXP créera un déploiement dans le projet hôte qui contient la règle de pare-feu VPC0 si aucune règle n'est spécifiée.
. Firewall.create et firewall.delete ne sont nécessaires que si vous ne passez pas de règles de pare-feu au déploiement et que vous choisissez de laisser BlueXP les créer pour vous. Ces autorisations résident dans le fichier .yaml du compte BlueXP. Si vous déployez une paire HA à l'aide d'un VPC partagé, ces autorisations seront utilisées pour créer les règles de pare-feu pour VPC1, 2 et 3. Pour tous les autres déploiements, ces autorisations seront également utilisées pour créer des règles pour VPC0.
. Pour le Tiering des données, le compte de service de Tiering doit avoir le rôle serviceAccount.user sur le compte de service, et pas seulement au niveau du projet. Actuellement, si vous attribuez serviceAccount.user au niveau du projet, les autorisations ne s'affichent pas lorsque vous interrogez le compte de service avec getIAMPolicy.


====