= 
:allow-uri-read: 


Créez un rôle et appliquez-le à un compte de service que vous utiliserez pour l'instance de la machine virtuelle Connector.

.Étapes
. Créez un rôle personnalisé dans Google Cloud :
+
.. Créez un fichier YAML qui inclut les autorisations définies dans le link:reference-permissions-gcp.html["Règle de connecteur pour Google Cloud"].
.. Dans Google Cloud, activez le shell cloud.
.. Téléchargez le fichier YAML qui inclut les autorisations requises pour le connecteur.
.. Créez un rôle personnalisé à l'aide de `gcloud iam roles create` commande.
+
L'exemple suivant crée un rôle nommé « connecteur » au niveau du projet :

+
[source, gcloud]
----
gcloud iam roles create connector --project=myproject --file=connector.yaml
----
+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Documents Google Cloud : création et gestion de rôles personnalisés"^]



. Créez un compte de service dans Google Cloud :
+
.. Dans le service IAM & Admin, sélectionnez *comptes de service > Créer un compte de service*.
.. Entrez les détails du compte de service et sélectionnez *Créer et continuer*.
.. Sélectionnez le rôle que vous venez de créer.
.. Terminez les étapes restantes pour créer le rôle.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Documents Google Cloud : création d'un compte de service"^]





.Résultat
Vous disposez désormais d'un compte de service que vous pouvez attribuer à l'instance VM Connector.
