= 
:allow-uri-read: 


.Avant de commencer
Vous devez disposer des éléments suivants :

* Privilèges root pour installer le connecteur.
* Détails sur un serveur proxy, si un proxy est requis pour accéder à Internet à partir du connecteur.
+
Vous avez la possibilité de configurer un serveur proxy après l'installation, mais cela nécessite de redémarrer le connecteur.

+
Notez que BlueXP ne prend pas en charge les serveurs proxy transparents.

* Un certificat signé par une autorité de certification, si le serveur proxy utilise HTTPS ou si le proxy est un proxy interceptant.


.Description de la tâche
Le programme d'installation disponible sur le site du support NetApp peut être une version antérieure. Après l'installation, le connecteur se met automatiquement à jour si une nouvelle version est disponible.

.Étapes
. Si les variables système _http_proxy_ ou _https_proxy_ sont définies sur l'hôte, supprimez-les :
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
Si vous ne supprimez pas ces variables système, l'installation échouera.

. Téléchargez le logiciel du connecteur à partir du https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["Site de support NetApp"^], Puis copiez-le sur l'hôte Linux.
+
Vous devez télécharger le programme d'installation du connecteur « en ligne » destiné à être utilisé sur votre réseau ou dans le cloud. Un programme d'installation séparé « hors ligne » est disponible pour le connecteur, mais il n'est pris en charge que pour les déploiements en mode privé.

. Attribuez des autorisations pour exécuter le script.
+
[source, cli]
----
chmod +x BlueXP-Connector-Cloud-<version>
----
+
Où <version> est la version du connecteur que vous avez téléchargé.

. Exécutez le script d'installation.
+
[source, cli]
----
 ./BlueXP-Connector-Cloud-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
Les paramètres --proxy et --cacert sont facultatifs. Si vous disposez d'un serveur proxy, vous devez entrer les paramètres comme indiqué. Le programme d'installation ne vous invite pas à fournir des informations sur un proxy.

+
Voici un exemple de commande utilisant les deux paramètres facultatifs :

+
[source, cli]
----
 ./BlueXP-Connector-Cloud-v3.9.40--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
--proxy configure le connecteur pour utiliser un serveur proxy HTTP ou HTTPS à l'aide de l'un des formats suivants :

+
** \http://address:port
** \http://user-name:password@address:port
** \http://domain-name%92user-name:password@address:port
** \https://address:port
** \https://user-name:password@address:port
** \https://domain-name%92user-name:password@address:port
+
Notez ce qui suit :

+
*** L'utilisateur peut être un utilisateur local ou un utilisateur de domaine.
*** Pour un utilisateur de domaine, vous devez utiliser le code ASCII pour un \ comme indiqué ci-dessus.
*** BlueXP ne prend pas en charge les noms d'utilisateur ou les mots de passe qui incluent le caractère @.
*** Si le mot de passe inclut l'un des caractères spéciaux suivants, vous devez échapper à ce caractère spécial en le préajoutant avec une barre oblique inverse : & ou !
+
Par exemple :

+
\http://bxpproxyuser:netapp1\!@address:3128





+
--cacert spécifie un certificat signé par une autorité de certification à utiliser pour l'accès HTTPS entre le connecteur et le serveur proxy. Ce paramètre est requis uniquement si vous spécifiez un serveur proxy HTTPS ou si le proxy est un proxy interceptant.



. Attendez la fin de l'installation.
+
À la fin de l'installation, le service connecteur (ocm) redémarre deux fois si vous avez spécifié un serveur proxy.

. Ouvrez un navigateur Web à partir d'un hôte connecté à la machine virtuelle Connector et entrez l'URL suivante :
+
https://_ipaddress_[]

. Une fois connecté, configurez le connecteur :
+
.. Spécifiez le compte BlueXP à associer au connecteur.
.. Entrez un nom pour le système.
.. Sous *exécutez-vous dans un environnement sécurisé ?* maintenez le mode restreint désactivé.
+
Vous devez désactiver le mode restreint, car ces étapes décrivent l'utilisation de BlueXP en mode standard. Vous devez activer le mode restreint uniquement si vous disposez d'un environnement sécurisé et souhaitez déconnecter ce compte des services back-end BlueXP. Si c'est le cas, link:task-quick-start-restricted-mode.html["Suivez les étapes pour démarrer avec BlueXP en mode restreint"].

.. Sélectionnez *commençons*.




.Résultat
Le connecteur est maintenant installé et configuré avec votre compte BlueXP.
